import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { wrap } from "@/server/lib/http";
import { requireSession } from "@/server/lib/auth";
import { explainIncident } from "@/server/services/ai/incident-explain";
import { env } from "@/server/lib/env";

const Query = z.object({
  // Bounded to prevent abuse — incident descriptions are short.
  desc: z.string().min(1).max(200),
});

export const dynamic = "force-dynamic";
export const maxDuration = 15;

// Auth-gated (anon device session qualifies) like the other /api/ai
// endpoints. Per-IP middleware cap and the cache layer further
// constrain cost.
//
// Routing: when API_BASE_URL is set, proxy to Railway so we hit the
// shared Redis-backed cache (route-parity Phase 2 — see audit summary).
// When unset, fall through to the in-process LRU implementation that
// shipped before the Railway migration.
export const GET = wrap(async (req: NextRequest) => {
  await requireSession(req);
  const { desc } = Query.parse(Object.fromEntries(req.nextUrl.searchParams));

  if (env.API_BASE_URL) {
    const url = `${env.API_BASE_URL.replace(/\/+$/, "")}/ai/incident-explain`;
    const upstream = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ description: desc }),
    }).catch(() => null);
    if (upstream?.ok) {
      const body = await upstream.json();
      return NextResponse.json({
        ...body,
        disclaimer:
          "Plain-language definition of the offense category, generated by AI. " +
          "Does not describe what specifically happened in this report.",
      });
    }
    // Soft-fall to local explainer on any upstream error — never block
    // the user just because Railway hiccuped.
  }

  const out = await explainIncident(desc);
  return NextResponse.json({
    explanation: out.explanation,
    cached: out.cached,
    aiConfigured: out.aiConfigured,
    disclaimer:
      "Plain-language definition of the offense category, generated by AI. " +
      "Does not describe what specifically happened in this report.",
  });
});
