import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { wrap } from "@/server/lib/http";
import { explainIncident } from "@/server/services/ai/incident-explain";
import { env } from "@/server/lib/env";

const Query = z.object({
  // Bounded to prevent abuse — incident descriptions are short.
  desc: z.string().min(1).max(200),
});

export const dynamic = "force-dynamic";
export const maxDuration = 15;

// fix(explain-cross-client): was requireSession-gated, which 401'd
// ("missing_bearer_token") for EVERY session-less client — the native
// WKWebView (cross-origin, no same-origin cs_session cookie), Safari ITP /
// third-party-cookie blocking, privacy modes, and the first-paint bootstrap
// race. The "Explain" link in every Local Activity (ThreatFeed) row then
// failed silently for those users, so the feature read as broken app-wide.
// Now PUBLIC — identical to /api/ai/area-brief and /api/ai/incident-summary —
// and still bounded: Vercel middleware caps /api/ai/* at 40/min per IP, and
// Railway's /ai/incident-explain caches per offense description (LLM runs once
// per unique offense, then free across rows and users).
//
// Routing: when API_BASE_URL is set, proxy to Railway so we hit the
// shared Redis-backed cache (route-parity Phase 2 — see audit summary).
// When unset, fall through to the in-process LRU implementation that
// shipped before the Railway migration.
export const GET = wrap(async (req: NextRequest) => {
  const { desc } = Query.parse(Object.fromEntries(req.nextUrl.searchParams));

  if (env.API_BASE_URL) {
    const url = `${env.API_BASE_URL.replace(/\/+$/, "")}/ai/incident-explain`;
    // fix(resilience upstream-no-timeout): a hung Railway upstream would block
    // this request until Vercel's function ceiling. 8s is ample for a cached/
    // short AI definition; on timeout AbortSignal rejects → .catch → null →
    // soft-fall to the local explainer below.
    const upstream = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ description: desc }),
      signal: AbortSignal.timeout(8000),
    }).catch(() => null);
    if (upstream?.ok) {
      const body = await upstream.json();
      return NextResponse.json({
        ...body,
        disclaimer:
          "Plain-language definition of the offense category, generated by AI. " +
          "Does not describe what specifically happened in this report.",
      });
    }
    // Soft-fall to local explainer on any upstream error — never block
    // the user just because Railway hiccuped.
  }

  const out = await explainIncident(desc);
  return NextResponse.json({
    explanation: out.explanation,
    cached: out.cached,
    aiConfigured: out.aiConfigured,
    disclaimer:
      "Plain-language definition of the offense category, generated by AI. " +
      "Does not describe what specifically happened in this report.",
  });
});
