import "server-only";
import { CrimeCategory } from "@prisma/client";
import { env } from "../../../lib/env";
import type { AreaStats, CrimeDataAdapter, DataProvenance, Incident } from "../types";
import type { KnownArea } from "../neighborhoods";
import { titleCaseOffense } from "../lib/titlecase-offense";
// Bundled snapshot of the BPD CSV (most recent 5,000 rows). Refreshed via
// `tools/refresh-boston.mjs` and committed to git. See "Why bundled?" below.
// Shipped as a TS module rather than a JSON import — Next's file-tracing
// has repeatedly missed JSON files in this path, but TS modules are always
// in the bundle.
import { bostonSnapshot as snapshot } from "../../../data/boston-snapshot";

// City of Boston — Crime Incident Reports (BPD).
//
// Why bundled? data.boston.gov returns 0 records when called directly from
// Vercel's IP range for any non-trivial response (limit=2 works, limit≥500
// silently empties — confirmed reproducible). Even paginated 100-row pulls
// fail. The CSV download endpoint redirects to a signed S3 URL that DOES
// work from Vercel, but downloading + parsing the 48 MB / 307k-row CSV on
// every cold start is wasteful.
//
// Hybrid path: snapshot the most-recent 5,000 rows of the CSV into
// /apps/web/data/boston-snapshot.json (~1 MB) and load that synchronously at
// module init. The snapshot is regenerated by `tools/refresh-boston.mjs`,
// committed to git, and ships with the build. When BOSTON_PROXY_URL is set
// (Cloudflare Worker deployed), we instead route live through the Worker
// for fresher data.
//
// CKAN doc: https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system

const RESOURCE_ID = "b973d8cb-eeb2-4e7e-99da-c92938efc9c0";
// datastore_search (NOT datastore_search_sql) — the SQL endpoint times out
// from Vercel's runtime against this dataset for any LIMIT above a few
// thousand. The simple search endpoint returns the same shape but supports
// limit/offset URL params with much better tail latency, and supports sort
// directly via &sort= so we still get the freshest rows first.
const SEARCH_BASE = "https://data.boston.gov/api/3/action/datastore_search";
// Boston's CKAN endpoint returns 0 records from Vercel's serverless
// runtime for any limit at 500 or above, but the limit=2 sanity probe
// returns 200 OK consistently. Strategy: pull in 10 paginated pages of
// 100 rows each = 1,000 fresh rows. If even small responses fail from
// Vercel, the failure is network-level (ASN block) and Boston should
// stay coming-soon.
const PAGE_SIZE = 100;
const PAGES = 10;
const CACHE_TTL_MS = 5 * 60 * 1000;
let cache: { fetchedAt: number; rows: Incident[] } | null = null;

interface BostonRow {
  INCIDENT_NUMBER?: string;
  OFFENSE_DESCRIPTION?: string;
  OFFENSE_CODE_GROUP?: string | null;
  DISTRICT?: string;
  OCCURRED_ON_DATE?: string;
  Lat?: string | null;
  Long?: string | null;
  SHOOTING?: string;
}

// BPD's offense descriptions are free-text and noisy. Substring match captures
// the bulk of cases without trying to encode every variant.
const PERSONS_KEYWORDS = [
  "ASSAULT", "ROBBERY", "MURDER", "HOMICIDE", "RAPE", "SEX",
  "HARASSMENT", "KIDNAP", "STALKING", "STRANGULATION",
];
const PROPERTY_KEYWORDS = [
  "THEFT", "LARCENY", "BURGLARY", "STOLEN", "ARSON",
  "VANDALISM", "PROPERTY DAMAGE", "MOTOR VEHICLE", "AUTO THEFT",
  "FORGERY", "FRAUD", "TRESPASS",
];
function mapToNibrs(row: BostonRow): CrimeCategory {
  const d = (row.OFFENSE_DESCRIPTION ?? "").toUpperCase();
  if (PERSONS_KEYWORDS.some((k) => d.includes(k))) return CrimeCategory.PERSONS;
  if (PROPERTY_KEYWORDS.some((k) => d.includes(k))) return CrimeCategory.PROPERTY;
  return CrimeCategory.SOCIETY;
}

// BPD's 12 districts, each mapped to the single most-recognized
// neighborhood in that district's coverage area. The prior labels
// were "A1: Downtown, North End, Beacon Hill, Chinatown" — verbose,
// non-standard versus other cities. v10 pass simplifies to single
// anchor names matching the Philadelphia / NOLA pattern.
const DISTRICT_NEIGHBORHOODS: Record<string, string> = {
  "A1":  "Downtown",
  "A7":  "East Boston",
  "A15": "Charlestown",
  "B2":  "Roxbury",
  "B3":  "Mattapan",
  "C6":  "South Boston",
  "C11": "Dorchester",
  "D4":  "Back Bay",
  "D14": "Allston",
  "E5":  "West Roxbury",
  "E13": "Jamaica Plain",
  "E18": "Hyde Park",
};

function enrich(district: string | undefined): string {
  if (!district) return "Unknown";
  const d = district.trim().toUpperCase();
  // Drop the district-code prefix per v10 simplification. Fall back
  // to "BPD District D" for unmapped codes so unknown districts
  // remain identifiable.
  return DISTRICT_NEIGHBORHOODS[d] ?? `BPD District ${d}`;
}

const PROVENANCE: DataProvenance = {
  source: "Boston Police Department Crime Incident Reports (City of Boston Open Data, CKAN)",
  datasetUrl: "https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system",
  recency: `Bundled snapshot from BPD CSV (generated ${snapshot.generated_at})`,
  granularity: "beat",
  disclaimer:
    "Incidents are reported by the Boston Police Department and aggregated to " +
    "BPD's 12 districts — not live, not street-level. CommunitySafe does not track individuals. " +
    "Boston data ships as a bundled snapshot because data.boston.gov rejects Vercel's IP " +
    "range; refresh by running `node tools/refresh-boston.mjs` and committing the result.",
};

function safeIsoFromBostonDate(raw: string | null | undefined): string {
  // BPD CSV stamps dates as "2026-04-21 02:49:00+00". The "+00" short-form
  // timezone offset is NOT a valid ECMAScript Date format — V8 parses it
  // as NaN. That dropped EVERY row's occurredAt to the 1970 epoch fallback,
  // which the citywide aggregator (safety-score.ts) then filtered out via
  // its `t > 0` invariant. Result: Boston citywide windowDays = 0 →
  // localPer100k = 0 → ratio 0.00 → BlockScore claimed Boston is "lower
  // than national" when really we couldn't compute anything.
  //
  // Fix: normalize the short offset to "+00:00" (RFC 3339 / spec-compliant)
  // before parsing. Also accept dates with no offset at all by appending
  // "Z" so they parse as UTC instead of local time (which would shift
  // every Boston incident by ±5 hours depending on Vercel POP region).
  if (!raw) return new Date(0).toISOString();
  let s = raw.replace(" ", "T");
  // Match a +HH or -HH offset that's NOT already followed by :MM.
  s = s.replace(/([+-]\d{2})$/, "$1:00");
  // No offset at all → declare UTC explicitly.
  if (!/[Zz]|[+-]\d{2}:?\d{2}$/.test(s)) s = s + "Z";
  const d = new Date(s);
  return Number.isNaN(d.getTime()) ? new Date(0).toISOString() : d.toISOString();
}

function rowsFromSnapshot(): Incident[] {
  return snapshot.rows.map((r, i) => {
    const lat = r.Lat ? Number(r.Lat) : NaN;
    const lon = r.Long ? Number(r.Long) : NaN;
    return {
      id: `bos-${r.INCIDENT_NUMBER ?? i}`,
      area: enrich(r.DISTRICT),
      occurredAt: safeIsoFromBostonDate(r.OCCURRED_ON_DATE),
      nibrsCategory: mapToNibrs({ OFFENSE_DESCRIPTION: r.OFFENSE_DESCRIPTION }),
      ibrOffenseDescription: titleCaseOffense(r.OFFENSE_DESCRIPTION),
      beat: r.DISTRICT ?? null,
      blockLabel: undefined,
      lat: !isNaN(lat) && lat !== 0 ? lat : undefined,
      lng: !isNaN(lon) && lon !== 0 ? lon : undefined,
    };
  });
}

function endpointBase(): string {
  // Route through the Cloudflare Worker proxy if configured. The Worker's
  // /datastore_search endpoint accepts the same CKAN query params we'd send
  // to data.boston.gov, so the only difference here is the URL host.
  const proxy = env.BOSTON_PROXY_URL;
  if (proxy) {
    const trimmed = proxy.replace(/\/+$/, "");
    return `${trimmed}/datastore_search`;
  }
  return SEARCH_BASE;
}

async function fetchPage(offset: number): Promise<BostonRow[]> {
  const sort = encodeURIComponent("OCCURRED_ON_DATE desc");
  const u = `${endpointBase()}?resource_id=${RESOURCE_ID}&limit=${PAGE_SIZE}&offset=${offset}&sort=${sort}`;
  const res = await fetch(u, {
    headers: {
      Accept: "application/json",
      "User-Agent": "Mozilla/5.0 CommunitySafe/0.1 (https://github.com/damienmcdade/CommunitySafe)",
    },
  });
  if (!res.ok) throw new Error(`Boston CKAN ${res.status} offset=${offset}`);
  const body = await res.json() as { success?: boolean; error?: unknown; result?: { records?: BostonRow[] } };
  if (body.success === false) throw new Error(`Boston CKAN error: ${JSON.stringify(body.error)}`);
  return body.result?.records ?? [];
}

async function fetchBoston(): Promise<Incident[]> {
  // Paginate in 100-row chunks. Large single-shot responses (≥500 rows) get
  // dropped on the Vercel→data.boston.gov hop for reasons we couldn't pin
  // down — small responses go through cleanly.
  const pages = await Promise.all(
    Array.from({ length: PAGES }, (_, i) => fetchPage(i * PAGE_SIZE).catch(() => [] as BostonRow[])),
  );
  const rows = pages.flat();
  return rows.map((r, i) => {
    const lat = Number(r.Lat);
    const lon = Number(r.Long);
    return {
      id: `bos-${r.INCIDENT_NUMBER ?? i}`,
      area: enrich(r.DISTRICT),
      occurredAt: safeIsoFromBostonDate(r.OCCURRED_ON_DATE),
      nibrsCategory: mapToNibrs(r),
      ibrOffenseDescription: titleCaseOffense(r.OFFENSE_DESCRIPTION),
      beat: r.DISTRICT ?? null,
      blockLabel: undefined,
      lat: !isNaN(lat) && lat !== 0 ? lat : undefined,
      lng: !isNaN(lon) && lon !== 0 ? lon : undefined,
    };
  });
}

export async function getRowsBoston(): Promise<Incident[]> {
  const now = Date.now();
  if (cache && cache.rows.length > 0 && now - cache.fetchedAt < CACHE_TTL_MS) return cache.rows;
  // If a Cloudflare Worker proxy is wired up, prefer live data — it's a few
  // weeks fresher than the bundled snapshot.
  if (env.BOSTON_PROXY_URL) {
    try {
      const rows = await fetchBoston();
      if (rows.length > 0) {
        cache = { fetchedAt: now, rows };
        return rows;
      }
    } catch (err) {
      console.warn("[boston] proxy fetch failed, falling back to snapshot:", (err as Error).message);
    }
  }
  // Fallback to bundled snapshot (works without any external infrastructure).
  const rows = rowsFromSnapshot();
  cache = { fetchedAt: now, rows };
  return rows;
}

export async function getDiscoveredAreasBoston(): Promise<KnownArea[]> {
  const rows = await getRowsBoston();
  const agg = new Map<string, { latSum: number; lngSum: number; count: number }>();
  for (const r of rows) {
    if (!r.area || r.area === "Unknown" || r.area === "External") continue;
    if (r.lat == null || r.lng == null) continue;
    const e = agg.get(r.area) ?? { latSum: 0, lngSum: 0, count: 0 };
    e.latSum += r.lat; e.lngSum += r.lng; e.count += 1;
    agg.set(r.area, e);
  }
  return Array.from(agg.entries())
    .filter(([, e]) => e.count >= 3)
    .map(([name, e]) => {
      // Slug from the neighborhood name itself ("Downtown" →
      // "bos-downtown"). Prior format was "bos-a1" (district-code
      // based) which became unreadable after v10 dropped the
      // district prefix. Existing bookmarks to "bos-a1" still
      // resolve via labelForBostonSlug's fallback to the old
      // district-code lookup.
      const nameSlug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
      return {
        slug: `bos-${nameSlug}`,
        label: name,
        jurisdiction: "Boston",
        centroid: { lat: e.latSum / e.count, lng: e.lngSum / e.count },
      };
    })
    .sort((a, b) => a.label.localeCompare(b.label));
}

function labelForBostonSlug(slug: string, rows: Incident[]): string | null {
  const s = slug.toLowerCase();
  const want = s.startsWith("bos-") ? s.slice(4) : s;
  // Modern slugs derive from the neighborhood name itself
  // (e.g., "bos-downtown" → "downtown" → matches r.area "Downtown").
  for (const r of rows) {
    const candidate = r.area.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    if (candidate === want) return r.area;
  }
  // Legacy bookmark fallback: old slugs were district-code-based
  // ("bos-a1" / "bos-b2"). Map district code → neighborhood name
  // by reading DISTRICT_NEIGHBORHOODS, then resolve through the
  // row data above.
  const wantUpper = want.toUpperCase();
  const legacy = DISTRICT_NEIGHBORHOODS[wantUpper];
  if (legacy) {
    for (const r of rows) if (r.area === legacy) return r.area;
  }
  return null;
}

export const bostonAdapter: CrimeDataAdapter = {
  name: "boston-ckan",

  async getAreaStats(area: string): Promise<AreaStats | null> {
    const rows = await getRowsBoston();
    const label = labelForBostonSlug(area, rows);
    if (!label) return null;
    const inArea = rows.filter((r) => r.area === label);
    if (inArea.length === 0) return null;
    const riskLevel: 1 | 2 | 3 | 4 | 5 = inArea.length > 1200 ? 5 : inArea.length > 700 ? 4 : inArea.length > 350 ? 3 : inArea.length > 120 ? 2 : 1;
    return { area: label, crimeRate: null, violentCrimeRate: null, propertyCrimeRate: null, riskLevel, provenance: PROVENANCE };
  },

  async getIncidents(area: string, opts?: { limit?: number; since?: Date }) {
    const rows = await getRowsBoston();
    const label = labelForBostonSlug(area, rows);
    if (!label) return [];
    let filtered = rows.filter((r) => r.area === label);
    if (opts?.since) filtered = filtered.filter((r) => new Date(r.occurredAt) >= opts.since!);
    filtered.sort((a, b) => +new Date(b.occurredAt) - +new Date(a.occurredAt));
    return filtered.slice(0, opts?.limit ?? 50);
  },

  async getRecentReports(area: string, opts?: { limit?: number }) {
    return this.getIncidents(area, { limit: opts?.limit ?? 20 });
  },
};
