// v96 — flat ESLint config for apps/web. Replaces the deprecated
// `next lint` legacy ESLint runner (Next 15 logs a deprecation
// warning every run; Next 16 removes it entirely). The
// FlatCompat shim wraps the `eslint-config-next` preset so we
// keep all the Next-specific React + a11y rules without
// rewriting them by hand.
//
// Also lets the husky pre-commit hook auto-fix staged web files
// via `eslint --fix` (was blocked because `next lint --fix
// --file ...` triggered an interactive config-picker prompt on
// every invocation).
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __dirname = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: __dirname });

export default [
  {
    // next-env.d.ts is regenerated by `next build`/`next dev` and
    // intentionally uses triple-slash references that
    // @typescript-eslint flags. Keeping it out of lint avoids a
    // permanent CI red without giving up the rule everywhere else.
    ignores: [".next/", "node_modules/", "dist/", "out/", "public/", "next-env.d.ts", "**/*.config.{js,mjs,ts}"],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];
