// Build VB_SUBDIVISION_PARENT: maps each of VB's ~1135 hyper-granular feed
// "Subdivision" slugs (e.g. vb-acqua-senior-apts, vb-abingdon-village-in-college-
// park) to one of the 333 REAL Virginia Beach neighbourhoods (the geojson /
// curated-population set), so every incident is re-labelled (never dropped) onto
// an area that HAS a curated population + polygon. Re-labelling is numerator-
// preserving: the citywide incident total is unchanged.
//
// Resolution order per feed slug:
//   1. direct  — the slug is already one of the 333 → maps to itself
//   2. "X in <Parent>" name parse → parent if it's one of the 333
//   3. point-in-polygon — the feed slug's resolved point (VB_AREA_CENTROIDS)
//      inside one of the 333 polygons
//   4. nearest — nearest of the 333 polygon centroids (catch-all)
//
// Run: cd packages/crime-data && ../../node_modules/.bin/tsx tools/build-vb-subdivision-parent.mts
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { VB_AREA_CENTROIDS } from "../src/data/virginia-beach-area-centroids.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GEOJSON = path.resolve(__dirname, "../../../apps/web/public/geo/virginia-beach.geojson");
const OUT = path.resolve(__dirname, "../src/data/virginia-beach-subdivision-parent.ts");

const slugify = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

interface Poly { name: string; rings: number[][][]; cx: number; cy: number; bbox: [number, number, number, number]; }

const geo = JSON.parse(fs.readFileSync(GEOJSON, "utf8")) as { features: Array<{ properties: { name: string }; geometry: { type: string; coordinates: unknown } }> };
const polys: Poly[] = [];
const canonicalByKey = new Map<string, string>();       // popKey -> canonical geojson name
for (const f of geo.features) {
  const name = f.properties.name;
  const key = `vb-${slugify(name)}`;
  canonicalByKey.set(key, name);
  const rings: number[][][] = f.geometry.type === "Polygon"
    ? (f.geometry.coordinates as number[][][])
    : (f.geometry.coordinates as number[][][][]).flat();
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity, sx = 0, sy = 0, n = 0;
  for (const ring of rings) for (const [x, y] of ring) {
    if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y;
    sx += x; sy += y; n++;
  }
  polys.push({ name, rings, cx: sx / n, cy: sy / n, bbox: [minX, minY, maxX, maxY] });
}
const popKeys = new Set(canonicalByKey.keys());

function pointInRing(x: number, y: number, ring: number[][]): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1], xj = ring[j][0], yj = ring[j][1];
    if (((yi > y) !== (yj > y)) && (x < ((xj - xi) * (y - yi)) / (yj - yi || 1e-12) + xi)) inside = !inside;
  }
  return inside;
}
function pip(lng: number, lat: number): string | null {
  for (const p of polys) {
    const [minX, minY, maxX, maxY] = p.bbox;
    if (lng < minX || lng > maxX || lat < minY || lat > maxY) continue;
    let parity = 0;
    for (const ring of p.rings) if (pointInRing(lng, lat, ring)) parity++;
    if (parity % 2 === 1) return p.name;
  }
  return null;
}
function nearest(lng: number, lat: number): string {
  let best = polys[0].name, bd = Infinity;
  for (const p of polys) { const d = (p.cx - lng) ** 2 + (p.cy - lat) ** 2; if (d < bd) { bd = d; best = p.name; } }
  return best;
}

// "abingdon village in college park" -> parent "college park"
function inParent(feedSlug: string): string | null {
  const words = feedSlug.replace(/^vb-/, "").replace(/-/g, " ");
  const idx = words.lastIndexOf(" in ");
  if (idx < 0) return null;
  const parentKey = `vb-${slugify(words.slice(idx + 4))}`;
  return popKeys.has(parentKey) ? canonicalByKey.get(parentKey)! : null;
}

const out: Record<string, string> = {};
const stats = { direct: 0, inParent: 0, pip: 0, nearest: 0, total: 0 };
for (const feedSlug of Object.keys(VB_AREA_CENTROIDS)) {
  stats.total++;
  let parent: string | undefined;
  if (popKeys.has(feedSlug)) { parent = canonicalByKey.get(feedSlug); stats.direct++; }
  if (!parent) { const p = inParent(feedSlug); if (p) { parent = p; stats.inParent++; } }
  if (!parent) {
    const c = (VB_AREA_CENTROIDS as Record<string, { lat: number; lng: number }>)[feedSlug];
    if (c) { const p = pip(c.lng, c.lat); if (p) { parent = p; stats.pip++; } else { parent = nearest(c.lng, c.lat); stats.nearest++; } }
  }
  if (parent) out[feedSlug] = parent;
}

// Emit sorted for stable diffs.
const sorted = Object.keys(out).sort();
const body = sorted.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(out[k])},`).join("\n");
const header = `// AUTO-GENERATED by tools/build-vb-subdivision-parent.mts — DO NOT EDIT BY HAND.
// Maps each VB feed "Subdivision" slug to one of the 333 real VB neighbourhoods
// (geojson / curated-population set). The adapter applies this per-incident so
// over-fragmented micro-areas (apartment complexes, "X in Parent" developments)
// roll up to a real neighbourhood WITH a curated population — a lossless
// re-label that preserves the citywide incident total. Regenerate after a feed
// refresh: cd packages/crime-data && ../../node_modules/.bin/tsx tools/build-vb-subdivision-parent.mts
export const VB_SUBDIVISION_PARENT: Record<string, string> = {
`;
fs.writeFileSync(OUT, header + body + "\n};\n");
console.log(`feed slugs: ${stats.total}`);
console.log(`resolved:   ${sorted.length} (${Math.round(sorted.length / stats.total * 100)}%)`);
console.log(`  direct=${stats.direct} inParent=${stats.inParent} pip=${stats.pip} nearest=${stats.nearest}`);
console.log(`distinct parents used: ${new Set(Object.values(out)).size} of ${polys.length} real neighbourhoods`);
console.log(`wrote ${OUT}`);
