// AUTO-GENERATED by tools/build-city-fbi-baselines.mjs
// Source: FBI Crime Data Explorer (api.usa.gov/crime/fbi/cde)
// per-agency annual rates per 100,000 residents.
//
// Each entry is the city's OWN FBI-published rate — the
// authoritative comparison anchor for citywide scoring. Used
// instead of the FBI national average, which is structurally
// pulled down by rural areas and makes every urban city
// collapse to grade E.
//
// DO NOT EDIT BY HAND. Re-run the build script after each new
// CDE month publishes.

export interface CityFbiBaseline {
  /// Per-100k annual rate for NIBRS Crimes Against Persons /
  /// UCR Violent Crime, summed across 12 months of the latest
  /// complete year.
  violent: number;
  /// Same for Crimes Against Property.
  property: number;
  /// Reporting year these rates apply to.
  year: number;
  /// FBI 9-character ORI for the city's reporting agency.
  ori: string;
}

export const CITY_FBI_BASELINES: Record<string, CityFbiBaseline> = {
  "baton-rouge": { violent: 1009, property: 5543, year: 2023, ori: "LA0170200" },
  "boise": { violent: 286, property: 850, year: 2025, ori: "ID0010100" },
  "boston": { violent: 582, property: 1914, year: 2025, ori: "MA0130100" },
  "buffalo": { violent: 729, property: 3414, year: 2025, ori: "NY0140100" },
  "cambridge": { violent: 436, property: 2601, year: 2025, ori: "MA0091100" },
  "charlotte": { violent: 559, property: 3418, year: 2025, ori: "NC0600100" },
  "chicago": { violent: 420, property: 2956, year: 2025, ori: "ILCPD0000" },
  "cincinnati": { violent: 779, property: 3599, year: 2025, ori: "OHCIP0000" },
  "cleveland": { violent: 1360, property: 3949, year: 2025, ori: "OHCLP0000" },
  "dallas": { violent: 576, property: 3070, year: 2025, ori: "TXDPD0000" },
  // Colorado Springs PD — CO0210100. Rates are approximations
  // pending a refresh via tools/build-city-fbi-baselines.mjs once
  // the FBI CDE API key is available; CSPD historically runs below
  // Denver on violent and near-national on property.
  "colorado-springs": { violent: 670, property: 3900, year: 2025, ori: "CO0210100" },
  "detroit": { violent: 1652, property: 3949, year: 2025, ori: "MI8234900" },
  "kansas-city": { violent: 1371, property: 3970, year: 2025, ori: "MOKPD0000" },
  "las-vegas": { violent: 409, property: 2418, year: 2025, ori: "NV0020100" },
  "los-angeles": { violent: 669, property: 2251, year: 2025, ori: "CA0194200" },
  "milwaukee": { violent: 1145, property: 2401, year: 2025, ori: "WIMPD0000" },
  "minneapolis": { violent: 1003, property: 4509, year: 2025, ori: "MN0271100" },
  "nashville": { violent: 955, property: 3862, year: 2025, ori: "TN0190100" },
  "new-orleans": { violent: 1361, property: 5090, year: 2023, ori: "LANPD0000" },
  "new-york": { violent: 658, property: 2288, year: 2025, ori: "NY0303000" },
  "norfolk": { violent: 397, property: 3176, year: 2025, ori: "VA1170000" },
  "oakland": { violent: 1475, property: 5255, year: 2025, ori: "CA0010900" },
  "philadelphia": { violent: 825, property: 4349, year: 2025, ori: "PAPEP0000" },
  "phoenix": { violent: 695, property: 2043, year: 2025, ori: "AZ0072300" },
  "pittsburgh": { violent: 470, property: 2364, year: 2025, ori: "PAPPD0000" },
  "saint-paul": { violent: 490, property: 2824, year: 2025, ori: "MN0620900" },
  "san-diego": { violent: 373, property: 1551, year: 2025, ori: "CA0371100" },
  "san-francisco": { violent: 486, property: 2960, year: 2025, ori: "CA0380100" },
  "seattle": { violent: 700, property: 4446, year: 2025, ori: "WASPD0000" },
  "washington-dc": { violent: 748, property: 3081, year: 2025, ori: "DCMPD0000" },
};
