// AUTO-GENERATED by tools/build-city-fbi-baselines.mjs
// Source: FBI Crime Data Explorer (api.usa.gov/crime/fbi/cde)
// per-agency annual rates per 100,000 residents.
//
// Each entry is the city's OWN FBI-published rate — the
// authoritative comparison anchor for citywide scoring. Used
// instead of the FBI national average, which is structurally
// pulled down by rural areas and makes every urban city
// collapse to grade E.
//
// DO NOT EDIT BY HAND. Re-run the build script after each new
// CDE month publishes.

export interface CityFbiBaseline {
  /// Per-100k annual rate for NIBRS Crimes Against Persons /
  /// UCR Violent Crime, summed across 12 months of the latest
  /// complete year.
  violent: number;
  /// Same for Crimes Against Property.
  property: number;
  /// Reporting year these rates apply to.
  year: number;
  /// FBI 9-character ORI for the city's reporting agency.
  ori: string;
}

export const CITY_FBI_BASELINES: Record<string, CityFbiBaseline> = {
  "baton-rouge": { violent: 398, property: 1118, year: 2025, ori: "LA0170100" },
  "boise": { violent: 286, property: 850, year: 2025, ori: "ID0010100" },
  "boston": { violent: 582, property: 1914, year: 2025, ori: "MA0130100" },
  "buffalo": { violent: 266, property: 1887, year: 2025, ori: "NY0140200" },
  "chicago": { violent: 420, property: 2956, year: 2025, ori: "ILCPD0000" },
  "cincinnati": { violent: 26, property: 494, year: 2025, ori: "OH0310200" },
  "cleveland": { violent: 106, property: 1363, year: 2025, ori: "OH0181800" },
  "dallas": { violent: 576, property: 3070, year: 2025, ori: "TXDPD0000" },
  "detroit": { violent: 1652, property: 3949, year: 2025, ori: "MI8234900" },
  "kansas-city": { violent: 301, property: 1156, year: 2025, ori: "MO0480000" },
  "los-angeles": { violent: 669, property: 2251, year: 2025, ori: "CA0194200" },
  "milwaukee": { violent: 1145, property: 2401, year: 2025, ori: "WIMPD0000" },
  "new-orleans": { violent: 1361, property: 5090, year: 2023, ori: "LANPD0000" },
  "new-york": { violent: 658, property: 2288, year: 2025, ori: "NY0303000" },
  "oakland": { violent: 1475, property: 5255, year: 2025, ori: "CA0010900" },
  "philadelphia": { violent: 825, property: 4349, year: 2025, ori: "PAPEP0000" },
  "phoenix": { violent: 86, property: 776, year: 2025, ori: "AZ0072700" },
  "pittsburgh": { violent: 470, property: 2364, year: 2025, ori: "PAPPD0000" },
  "saint-paul": { violent: 490, property: 2824, year: 2025, ori: "MN0620900" },
  "san-diego": { violent: 373, property: 1551, year: 2025, ori: "CA0371100" },
  "san-francisco": { violent: 486, property: 2960, year: 2025, ori: "CA0380100" },
  "seattle": { violent: 75, property: 1009, year: 2025, ori: "WA0171000" },
  "washington-dc": { violent: 748, property: 3081, year: 2025, ori: "DCMPD0000" },
};
