import { CrimeCategory } from "../crime-category.js";
import { readJson } from "../lib/http.js";
import { env } from "../env.js";
import type { AreaStats, CrimeDataAdapter, DataProvenance, Incident } from "../types.js";
import { registerRowCache } from "../cache-registry.js";
import { riskLevelFromAreaCounts } from "../risk-bands.js";
import type { KnownArea } from "../neighborhoods.js";
import { titleCaseOffense } from "../lib/titlecase-offense.js";
// Bundled snapshot of the BPD CSV (most recent 5,000 rows). Refreshed via
// `tools/refresh-boston.mjs` and committed to git. See "Why bundled?" below.
// Shipped as a TS module rather than a JSON import — Next's file-tracing
// has repeatedly missed JSON files in this path, but TS modules are always
// in the bundle.
import { bostonSnapshot as snapshot } from "../data/boston-snapshot.js";
import { bostonPolygons } from "../data/boston-neighborhoods.js";

// City of Boston — Crime Incident Reports (BPD).
//
// Why bundled? data.boston.gov returns 0 records when called directly from
// Vercel's IP range for any non-trivial response (limit=2 works, limit≥500
// silently empties — confirmed reproducible). Even paginated 100-row pulls
// fail. The CSV download endpoint redirects to a signed S3 URL that DOES
// work from Vercel, but downloading + parsing the 48 MB / 307k-row CSV on
// every cold start is wasteful.
//
// Hybrid path: snapshot the most-recent 5,000 rows of the CSV into
// /apps/web/data/boston-snapshot.json (~1 MB) and load that synchronously at
// module init. The snapshot is regenerated by `tools/refresh-boston.mjs`,
// committed to git, and ships with the build. When BOSTON_PROXY_URL is set
// (Cloudflare Worker deployed), we instead route live through the Worker
// for fresher data.
//
// CKAN doc: https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system

const RESOURCE_ID = "b973d8cb-eeb2-4e7e-99da-c92938efc9c0";
// datastore_search (NOT datastore_search_sql) — the SQL endpoint times out
// from Vercel's runtime against this dataset for any LIMIT above a few
// thousand. The simple search endpoint returns the same shape but supports
// limit/offset URL params with much better tail latency, and supports sort
// directly via &sort= so we still get the freshest rows first.
const SEARCH_BASE = "https://data.boston.gov/api/3/action/datastore_search";
// Boston's CKAN endpoint returns 0 records from Vercel's serverless
// runtime for any limit at 500 or above, but the limit=2 sanity probe
// returns 200 OK consistently. Strategy: pull in 10 paginated pages of
// 100 rows each = 1,000 fresh rows. If even small responses fail from
// Vercel, the failure is network-level (ASN block) and Boston should
// stay coming-soon.
const PAGE_SIZE = 100;
const PAGES = 10;
const CACHE_TTL_MS = 5 * 60 * 1000;
let cache: { fetchedAt: number; rows: Incident[] } | null = null;
registerRowCache(() => { cache = null; }, "boston-ckan");

// v70 — direct CSV download path. The data.boston.gov CSV-download
// endpoint redirects to a signed S3 URL (24h pre-signed). S3 is
// wide-open by IP, so this WORKS from both Vercel and Railway even
// though the CKAN API endpoint silently 0-records from Vercel.
// 45MB / 307k lines / 3s fetch on Railway; we keep the most-recent
// 30k rows in cache. Longer TTL (30min) because BPD publishes
// daily, not real-time.
const CSV_URL = "https://data.boston.gov/dataset/6220d948-eae2-4e4b-8723-2dc8e67722a3/resource/b973d8cb-eeb2-4e7e-99da-c92938efc9c0/download/tmpcyl1hw5w.csv";
const CSV_ROWS_TO_KEEP = 30_000;
const CSV_CACHE_TTL_MS = 30 * 60 * 1000;

interface BostonRow {
  INCIDENT_NUMBER?: string;
  OFFENSE_DESCRIPTION?: string;
  OFFENSE_CODE_GROUP?: string | null;
  DISTRICT?: string;
  OCCURRED_ON_DATE?: string;
  Lat?: string | null;
  Long?: string | null;
  SHOOTING?: string;
}

// BPD's offense descriptions are free-text and noisy. Substring match captures
// the bulk of cases without trying to encode every variant.
const PERSONS_KEYWORDS = [
  "ASSAULT", "ROBBERY", "MURDER", "HOMICIDE", "RAPE", "SEX",
  "HARASSMENT", "KIDNAP", "STALKING", "STRANGULATION",
];
const PROPERTY_KEYWORDS = [
  "THEFT", "LARCENY", "BURGLARY", "STOLEN", "ARSON",
  "VANDALISM", "PROPERTY DAMAGE", "MOTOR VEHICLE", "AUTO THEFT",
  "FORGERY", "FRAUD", "TRESPASS",
];
function mapToNibrs(row: BostonRow): CrimeCategory {
  const d = (row.OFFENSE_DESCRIPTION ?? "").toUpperCase();
  if (PERSONS_KEYWORDS.some((k) => d.includes(k))) return CrimeCategory.PERSONS;
  if (PROPERTY_KEYWORDS.some((k) => d.includes(k))) return CrimeCategory.PROPERTY;
  return CrimeCategory.SOCIETY;
}

// BPD's 12 districts, each mapped to the single most-recognized
// neighborhood in that district's coverage area. The prior labels
// were "A1: Downtown, North End, Beacon Hill, Chinatown" — verbose,
// non-standard versus other cities. v10 pass simplifies to single
// anchor names matching the Philadelphia / NOLA pattern.
const DISTRICT_NEIGHBORHOODS: Record<string, string> = {
  "A1":  "Downtown",
  "A7":  "East Boston",
  "A15": "Charlestown",
  "B2":  "Roxbury",
  "B3":  "Mattapan",
  "C6":  "South Boston",
  "C11": "Dorchester",
  "D4":  "Back Bay",
  "D14": "Allston",
  "E5":  "West Roxbury",
  "E13": "Jamaica Plain",
  "E18": "Hyde Park",
};

function enrich(district: string | undefined): string {
  if (!district) return "Unknown";
  const d = district.trim().toUpperCase();
  // Drop the district-code prefix per v10 simplification. Fall back
  // to "BPD District D" for unmapped codes so unknown districts
  // remain identifiable.
  return DISTRICT_NEIGHBORHOODS[d] ?? `BPD District ${d}`;
}

// v97 — neighborhood-level upgrade. BPD rows carry Lat/Long, so each
// incident can be geocoded into one of the 26 official Boston
// neighborhoods (blackmad/neighborhoods) via bbox-prefiltered ray
// casting — same self-contained pattern as the Philadelphia / New
// Orleans adapters. This lifts Boston from 12 district anchors to 26
// neighborhoods. Rows without usable coordinates fall back to the
// district→anchor mapping so coverage never regresses.
interface PolyIndex { name: string; bbox: [number, number, number, number]; rings: number[][][] }
const POLY_INDEX: PolyIndex[] = bostonPolygons.map((p) => {
  const rings: number[][][] = p.geometry.type === "Polygon"
    ? (p.geometry.coordinates as number[][][])
    : (p.geometry.coordinates as number[][][][]).flat();
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const ring of rings) for (const [x, y] of ring) {
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
  }
  return { name: p.name, bbox: [minX, minY, maxX, maxY], rings };
});

function pointInRing(x: number, y: number, ring: number[][]): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1], xj = ring[j][0], yj = ring[j][1];
    const intersect = ((yi > y) !== (yj > y)) && (x < ((xj - xi) * (y - yi)) / (yj - yi || 1e-12) + xi);
    if (intersect) inside = !inside;
  }
  return inside;
}

function geocodeBoston(lng: number, lat: number): string | null {
  for (const p of POLY_INDEX) {
    const [minX, minY, maxX, maxY] = p.bbox;
    if (lng < minX || lng > maxX || lat < minY || lat > maxY) continue;
    let parity = 0;
    for (const ring of p.rings) if (pointInRing(lng, lat, ring)) parity++;
    if (parity % 2 === 1) return p.name;
  }
  return null;
}

// Geocode by coordinate when available; else fall back to the BPD
// district anchor. NaN/0 coordinates (BPD's null-island sentinel) skip
// straight to the district fallback.
function areaForBoston(lat: number, lon: number, district: string | undefined): string {
  if (!Number.isNaN(lat) && !Number.isNaN(lon) && lat !== 0 && lon !== 0) {
    const hood = geocodeBoston(lon, lat);
    if (hood) return hood;
  }
  return enrich(district);
}

const PROVENANCE: DataProvenance = {
  source: "Boston Police Department Crime Incident Reports (City of Boston Open Data, CKAN)",
  datasetUrl: "https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system",
  recency: `Bundled snapshot from BPD CSV (generated ${snapshot.generated_at})`,
  granularity: "neighborhood",
  disclaimer:
    "Incidents are reported by the Boston Police Department and geocoded to one of " +
    "26 official Boston neighborhoods (incidents without coordinates fall back to BPD's " +
    "12 districts) — not live, not street-level. CommunitySafe does not track individuals. " +
    "Boston data ships as a bundled snapshot because data.boston.gov rejects Vercel's IP " +
    "range; refresh by running `node tools/refresh-boston.mjs` and committing the result.",
};

function safeIsoFromBostonDate(raw: string | null | undefined): string {
  // BPD CSV stamps dates as "2026-04-21 02:49:00+00". The "+00" short-form
  // timezone offset is NOT a valid ECMAScript Date format — V8 parses it
  // as NaN. That dropped EVERY row's occurredAt to the 1970 epoch fallback,
  // which the citywide aggregator (safety-score.ts) then filtered out via
  // its `t > 0` invariant. Result: Boston citywide windowDays = 0 →
  // localPer100k = 0 → ratio 0.00 → BlockScore claimed Boston is "lower
  // than national" when really we couldn't compute anything.
  //
  // Fix: normalize the short offset to "+00:00" (RFC 3339 / spec-compliant)
  // before parsing. Also accept dates with no offset at all by appending
  // "Z" so they parse as UTC instead of local time (which would shift
  // every Boston incident by ±5 hours depending on Vercel POP region).
  if (!raw) return new Date(0).toISOString();
  let s = raw.replace(" ", "T");
  // Match a +HH or -HH offset that's NOT already followed by :MM.
  s = s.replace(/([+-]\d{2})$/, "$1:00");
  // No offset at all → declare UTC explicitly.
  if (!/[Zz]|[+-]\d{2}:?\d{2}$/.test(s)) s = s + "Z";
  const d = new Date(s);
  return Number.isNaN(d.getTime()) ? new Date(0).toISOString() : d.toISOString();
}

function rowsFromSnapshot(): Incident[] {
  return snapshot.rows.map((r, i) => {
    const lat = r.Lat ? Number(r.Lat) : NaN;
    const lon = r.Long ? Number(r.Long) : NaN;
    return {
      id: `bos-${r.INCIDENT_NUMBER ?? i}`,
      area: areaForBoston(lat, lon, r.DISTRICT),
      occurredAt: safeIsoFromBostonDate(r.OCCURRED_ON_DATE),
      nibrsCategory: mapToNibrs({ OFFENSE_DESCRIPTION: r.OFFENSE_DESCRIPTION }),
      ibrOffenseDescription: titleCaseOffense(r.OFFENSE_DESCRIPTION),
      beat: r.DISTRICT ?? null,
      blockLabel: undefined,
      lat: !isNaN(lat) && lat !== 0 ? lat : undefined,
      lng: !isNaN(lon) && lon !== 0 ? lon : undefined,
    };
  });
}

function endpointBase(): string {
  // Route through the Cloudflare Worker proxy if configured. The Worker's
  // /datastore_search endpoint accepts the same CKAN query params we'd send
  // to data.boston.gov, so the only difference here is the URL host.
  const proxy = env.BOSTON_PROXY_URL;
  if (proxy) {
    const trimmed = proxy.replace(/\/+$/, "");
    return `${trimmed}/datastore_search`;
  }
  return SEARCH_BASE;
}

async function fetchPage(offset: number): Promise<BostonRow[]> {
  const sort = encodeURIComponent("OCCURRED_ON_DATE desc");
  const u = `${endpointBase()}?resource_id=${RESOURCE_ID}&limit=${PAGE_SIZE}&offset=${offset}&sort=${sort}`;
  const res = await fetch(u, {
    headers: {
      Accept: "application/json",
      "User-Agent": "Mozilla/5.0 CommunitySafe/0.1 (https://github.com/damienmcdade/TravelSafe)",
    },
    signal: AbortSignal.timeout(45_000),
  });
  if (!res.ok) throw new Error(`Boston CKAN ${res.status} offset=${offset}`);
  const body = await readJson(res) as { success?: boolean; error?: unknown; result?: { records?: BostonRow[] } };
  if (body.success === false) throw new Error(`Boston CKAN error: ${JSON.stringify(body.error)}`);
  return body.result?.records ?? [];
}

async function fetchBoston(): Promise<Incident[]> {
  // Paginate in 100-row chunks. Large single-shot responses (≥500 rows) get
  // dropped on the Vercel→data.boston.gov hop for reasons we couldn't pin
  // down — small responses go through cleanly.
  const pages = await Promise.all(
    Array.from({ length: PAGES }, (_, i) => fetchPage(i * PAGE_SIZE).catch(() => [] as BostonRow[])),
  );
  const rows = pages.flat();
  return rows.map((r, i) => {
    const lat = Number(r.Lat);
    const lon = Number(r.Long);
    return {
      id: `bos-${r.INCIDENT_NUMBER ?? i}`,
      area: areaForBoston(lat, lon, r.DISTRICT),
      occurredAt: safeIsoFromBostonDate(r.OCCURRED_ON_DATE),
      nibrsCategory: mapToNibrs(r),
      ibrOffenseDescription: titleCaseOffense(r.OFFENSE_DESCRIPTION),
      beat: r.DISTRICT ?? null,
      blockLabel: undefined,
      lat: !isNaN(lat) && lat !== 0 ? lat : undefined,
      lng: !isNaN(lon) && lon !== 0 ? lon : undefined,
    };
  });
}

// v70 — quote-aware CSV row splitter. BPD CSV embeds commas inside
// quoted Location strings ("(lat, lng)") and OFFENSE_DESCRIPTION
// occasionally has commas too — naive split corrupts column indexes.
function splitCSVRow(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') inQuotes = false;
      else cur += ch;
    } else {
      if (ch === '"') inQuotes = true;
      else if (ch === ",") { out.push(cur); cur = ""; }
      else cur += ch;
    }
  }
  out.push(cur);
  return out;
}

async function fetchBostonFromCSV(): Promise<Incident[]> {
  const res = await fetch(CSV_URL, {
    redirect: "follow",
    headers: { "User-Agent": "CommunitySafe/1.0 (https://github.com/damienmcdade/TravelSafe)" },
    signal: AbortSignal.timeout(45_000),
  });
  if (!res.ok) throw new Error(`Boston CSV ${res.status}`);
  // v90p6 — reverted v88's readline+stream streaming because the
  // dynamic `await import("node:readline")` was still statically
  // analyzed by webpack and broke the Vercel bundle (same root
  // cause as the undici split-failure). text+split costs ~90MB
  // peak but only runs in apps/api (Railway) where the 512MB
  // container has headroom. If/when we wire next.config
  // serverExternalPackages, we can restore streaming.
  const text = await res.text();
  const lines = text.split("\n");
  if (lines.length < 2) throw new Error("Boston CSV: empty");
  const headers = splitCSVRow(lines[0]);
  const idx: Record<string, number> = {};
  for (const [i, h] of headers.entries()) idx[h] = i;
  type ParsedRow = { ts: number; row: BostonRow };
  const parsed: ParsedRow[] = [];
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    if (!line) continue;
    const f = splitCSVRow(line);
    const dateStr = f[idx.OCCURRED_ON_DATE];
    if (!dateStr) continue;
    const iso = dateStr.replace(" ", "T").replace(/([+-]\d{2})$/, "$1:00");
    const ts = Date.parse(iso);
    if (!Number.isFinite(ts)) continue;
    parsed.push({
      ts,
      row: {
        INCIDENT_NUMBER: f[idx.INCIDENT_NUMBER] || "",
        OFFENSE_DESCRIPTION: (f[idx.OFFENSE_DESCRIPTION] || "").trim(),
        OFFENSE_CODE_GROUP: f[idx.OFFENSE_CODE_GROUP] || null,
        DISTRICT: f[idx.DISTRICT] || "",
        OCCURRED_ON_DATE: dateStr,
        Lat: f[idx.Lat] || null,
        Long: f[idx.Long] || null,
        SHOOTING: f[idx.SHOOTING] || "",
      },
    });
  }
  parsed.sort((a, b) => b.ts - a.ts);
  const top = parsed.slice(0, CSV_ROWS_TO_KEEP);
  return top.map(({ row }, i) => {
    const lat = Number(row.Lat);
    const lon = Number(row.Long);
    return {
      id: `bos-${row.INCIDENT_NUMBER || i}`,
      area: areaForBoston(lat, lon, row.DISTRICT),
      occurredAt: safeIsoFromBostonDate(row.OCCURRED_ON_DATE),
      nibrsCategory: mapToNibrs(row),
      ibrOffenseDescription: titleCaseOffense(row.OFFENSE_DESCRIPTION),
      beat: row.DISTRICT ?? null,
      blockLabel: undefined,
      lat: !isNaN(lat) && lat !== 0 ? lat : undefined,
      lng: !isNaN(lon) && lon !== 0 ? lon : undefined,
    };
  });
}

// v107 — in-flight fetch dedup (the OOM-guard Detroit added in v94): the
// dispatcher fans a per-area Promise.all over every neighbourhood, so a cold
// cache previously fired N concurrent CSV downloads (~45MB each). Concurrent
// callers now await the same promise.
let inFlightBostonFetch: Promise<Incident[]> | null = null;
export async function getRowsBoston(): Promise<Incident[]> {
  const now = Date.now();
  // v70 — CSV cache has its own longer TTL (30min) because BPD only
  // publishes daily; refreshing every 5min on a 45MB download wastes
  // bandwidth without producing new data.
  if (cache && cache.rows.length > 0 && now - cache.fetchedAt < CSV_CACHE_TTL_MS) return cache.rows;
  if (inFlightBostonFetch) return inFlightBostonFetch;
  inFlightBostonFetch = (async () => {
    try {
      // PRIMARY PATH: direct CSV download (S3-signed, works from any IP).
      // This bypasses the data.boston.gov IP-blocking that hit the CKAN
      // API path. Returns 20-30k rows of recent BPD incidents in ~3-5s
      // total (3s fetch + 1-2s parse).
      try {
        const rows = await fetchBostonFromCSV();
        if (rows.length > 0) {
          cache = { fetchedAt: now, rows };
          return rows;
        }
      } catch (err) {
        console.warn("[boston] CSV fetch failed, trying CKAN/snapshot fallbacks:", (err as Error).message);
      }

      // SECONDARY: Cloudflare Worker → CKAN proxy if configured.
      if (env.BOSTON_PROXY_URL) {
        try {
          const rows = await fetchBoston();
          if (rows.length > 0) {
            cache = { fetchedAt: now, rows };
            return rows;
          }
        } catch (err) {
          console.warn("[boston] proxy fetch failed, falling back to snapshot:", (err as Error).message);
        }
      }

      // LAST RESORT: bundled snapshot (5k rows committed at build time).
      // Stays in sync via the GitHub Actions weekly refresh workflow.
      const rows = rowsFromSnapshot();
      cache = { fetchedAt: now, rows };
      return rows;
    } finally {
      inFlightBostonFetch = null;
    }
  })();
  return inFlightBostonFetch;
}

export async function getDiscoveredAreasBoston(): Promise<KnownArea[]> {
  const rows = await getRowsBoston();
  const agg = new Map<string, { latSum: number; lngSum: number; count: number }>();
  for (const r of rows) {
    if (!r.area || r.area === "Unknown") continue;
    // v95p36 — drop ALL "External" placeholder labels. The original
    // filter only matched "External" exactly, but enrich() produces
    // "BPD District EXTERNAL" for unmapped district codes, which was
    // surfacing to users as an unrecognizable "neighborhood". Case-
    // insensitive check covers both shapes.
    if (/external/i.test(r.area)) continue;
    if (r.lat == null || r.lng == null) continue;
    const e = agg.get(r.area) ?? { latSum: 0, lngSum: 0, count: 0 };
    e.latSum += r.lat; e.lngSum += r.lng; e.count += 1;
    agg.set(r.area, e);
  }
  return Array.from(agg.entries())
    .filter(([, e]) => e.count >= 3)
    .map(([name, e]) => {
      // Slug from the neighborhood name itself ("Downtown" →
      // "bos-downtown"). Prior format was "bos-a1" (district-code
      // based) which became unreadable after v10 dropped the
      // district prefix. Existing bookmarks to "bos-a1" still
      // resolve via labelForBostonSlug's fallback to the old
      // district-code lookup.
      const nameSlug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
      return {
        slug: `bos-${nameSlug}`,
        label: name,
        jurisdiction: "Boston",
        centroid: { lat: e.latSum / e.count, lng: e.lngSum / e.count },
      };
    })
    .sort((a, b) => a.label.localeCompare(b.label));
}

function labelForBostonSlug(slug: string, rows: Incident[]): string | null {
  const s = slug.toLowerCase();
  const want = s.startsWith("bos-") ? s.slice(4) : s;
  // Modern slugs derive from the neighborhood name itself
  // (e.g., "bos-downtown" → "downtown" → matches r.area "Downtown").
  for (const r of rows) {
    const candidate = r.area.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    if (candidate === want) return r.area;
  }
  // Legacy bookmark fallback: old slugs were district-code-based
  // ("bos-a1" / "bos-b2"). Map district code → neighborhood name
  // by reading DISTRICT_NEIGHBORHOODS, then resolve through the
  // row data above.
  const wantUpper = want.toUpperCase();
  const legacy = DISTRICT_NEIGHBORHOODS[wantUpper];
  if (legacy) {
    for (const r of rows) if (r.area === legacy) return r.area;
  }
  return null;
}

export const bostonAdapter: CrimeDataAdapter = {
  name: "boston-ckan",

  async getAreaStats(area: string): Promise<AreaStats | null> {
    const rows = await getRowsBoston();
    const label = labelForBostonSlug(area, rows);
    if (!label) return null;
    const inArea = rows.filter((r) => r.area === label);
    if (inArea.length === 0) return null;
    const riskLevel = riskLevelFromAreaCounts(rows, inArea.length, [120, 350, 700, 1200]);
    return { area: label, crimeRate: null, violentCrimeRate: null, propertyCrimeRate: null, riskLevel, provenance: PROVENANCE };
  },

  async getIncidents(area: string, opts?: { limit?: number; since?: Date }) {
    const rows = await getRowsBoston();
    const label = labelForBostonSlug(area, rows);
    if (!label) return [];
    let filtered = rows.filter((r) => r.area === label);
    if (opts?.since) filtered = filtered.filter((r) => new Date(r.occurredAt) >= opts.since!);
    filtered.sort((a, b) => +new Date(b.occurredAt) - +new Date(a.occurredAt));
    return filtered.slice(0, opts?.limit ?? 50);
  },

  async getRecentReports(area: string, opts?: { limit?: number }) {
    return this.getIncidents(area, { limit: opts?.limit ?? 20 });
  },
};
