import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy",
  description:
    "TravelSafe privacy practices — what's stored on your device, what we don't collect, and how to control it.",
};

const LAST_UPDATED = "2026-05-22";

export default function PrivacyPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-10 space-y-6">
      <header>
        <p className="text-xs uppercase tracking-[0.18em] text-bay-700 font-medium">Legal</p>
        <h1 className="mt-1 font-display text-3xl text-slate2-900">Privacy</h1>
        <p className="mt-2 text-xs text-slate2-500">Last updated: {LAST_UPDATED}</p>
      </header>

      <section className="surface p-6 space-y-3 text-sm text-slate2-700 leading-relaxed">
        <h2 className="font-display text-xl text-slate2-900">What TravelSafe does NOT collect</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>No account, no email, no phone number to browse the app.</li>
          <li>No demographic data — race, ethnicity, religion, age, gender, sexual orientation are not stored, displayed, or analyzed anywhere in the app.</li>
          <li>No individual identification — police data is aggregated to neighborhood-level only; individuals&apos; names, addresses, plates, or photos are never surfaced.</li>
          <li>No location tracking. Geolocation is requested only when you tap &quot;Use my location&quot;, used once for the lookup, and not stored.</li>
          <li>No third-party advertising, no analytics that profile individuals, no shared cookies.</li>
        </ul>
      </section>

      <section className="surface p-6 space-y-3 text-sm text-slate2-700 leading-relaxed">
        <h2 className="font-display text-xl text-slate2-900">What is stored on your device</h2>
        <p>TravelSafe uses your browser&apos;s <strong>localStorage</strong> to remember preferences and speed up subsequent loads. Nothing in localStorage is transmitted to TravelSafe&apos;s servers beyond the anonymous session token required to access protected endpoints.</p>
        <ul className="list-disc pl-5 space-y-1">
          <li><code className="text-xs">travelsafe.token</code> — anonymous session JWT, minted per-device on first visit.</li>
          <li><code className="text-xs">travelsafe.city.v1</code> — currently-selected city.</li>
          <li><code className="text-xs">travelsafe.area.v1</code> — currently-picked neighborhood, per city.</li>
          <li><code className="text-xs">travelsafe.saved-areas.v1</code> — your saved neighborhoods (up to 5).</li>
          <li><code className="text-xs">travelsafe.swr.v1.*</code> — cached API responses for snappy navigation (15-min TTL).</li>
          <li><code className="text-xs">travelsafe.safety.disclaimer.ack</code> — flag that you&apos;ve dismissed the Personal Safety disclaimer.</li>
          <li><code className="text-xs">travelsafe.assistant.*</code> — your AI Assistant conversation history (stored locally so you can review past answers).</li>
        </ul>
        <p>To clear everything: open your browser settings and delete site data for this domain, or open DevTools → Application → Local Storage → clear.</p>
      </section>

      <section className="surface p-6 space-y-3 text-sm text-slate2-700 leading-relaxed">
        <h2 className="font-display text-xl text-slate2-900">What we receive when you use the app</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>Standard server logs (IP address, user-agent, request path, timestamp) generated by the Vercel platform. Retained per Vercel&apos;s default retention.</li>
          <li>When you submit a Community post: the post body, neighborhood, and the anonymous session token associated with the device that posted.</li>
          <li>When you arm a Check-In timer or generate a Live Share link: the duration, optional note, and the location coordinates you choose to share at that moment.</li>
        </ul>
        <p>We do not sell, license, or share user data with third parties for advertising or marketing.</p>
      </section>

      <section className="surface p-6 space-y-3 text-sm text-slate2-700 leading-relaxed">
        <h2 className="font-display text-xl text-slate2-900">Public data sources we display</h2>
        <p>TravelSafe surfaces police-incident data that the cities themselves publish through their official open-data portals (SDPD, LAPD, SFPD, Chicago CPD, NYPD, and 24 others). We do not augment, predict, or editorialize that data. The FBI national-rate comparison comes from the FBI Crime in the Nation 2024 release at <a href="https://cde.ucr.cjis.gov/LATEST/webapp/" target="_blank" rel="noreferrer" className="text-bay-700 hover:underline">cde.ucr.cjis.gov</a>.</p>
      </section>

      <section className="surface p-6 space-y-3 text-sm text-slate2-700 leading-relaxed">
        <h2 className="font-display text-xl text-slate2-900">GDPR / CCPA</h2>
        <p>Because TravelSafe does not require an account and does not store personally identifiable information server-side beyond what you explicitly submit (Community posts, Check-In notes, Live Share recipients), there is no individual profile to access, port, or delete. To delete your locally-stored preferences, follow the steps in <strong>What is stored on your device</strong> above. To delete a Community post you submitted, use the post&apos;s Report button — moderation will review.</p>
      </section>

      <section className="surface p-6 space-y-2 text-sm text-slate2-700 leading-relaxed">
        <h2 className="font-display text-xl text-slate2-900">Contact</h2>
        <p>Questions or requests: open an issue at the project&apos;s GitHub repository, or use the Report link inside the app for content concerns.</p>
      </section>

      <p className="text-xs text-slate2-500">
        See also: <Link href="/terms" className="text-bay-700 hover:underline">Terms of use</Link>.
      </p>
    </main>
  );
}
