// v106 — moved out of CityBackdrop.tsx (a "use client" module). The server
// /credits page imports PHOTOS to render attribution; importing it from a
// client module pulled the entire URL map into a client chunk on a static
// legal page. Living in this plain module, /credits consumes it at build time
// with zero client JS, and CityBackdrop still imports it for the rotation.
//
// Each city carries 8 verified Wikimedia Commons landscape photos rendered at
// 1920x1080 (1080p) — the standard Commons 1920px thumb width — rotating every
// 30 seconds (see CityBackdrop ROTATE_MS). URLs are resolved + HTTP-verified
// via the Commons imageinfo API (tools/photos.mjs): mime image/jpeg|png,
// landscape (w/h >= 1.25), min 1200px source. Keyed by city slug.

export const PHOTOS: Record<string, string[]> = {
  "san-diego": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/San_Diego_skyline_18_%28cropped%29.jpg/1920px-San_Diego_skyline_18_%28cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Downtown_San_Diego_02.jpg/1920px-Downtown_San_Diego_02.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Petco_Park%2C_San_Diego.jpg/1920px-Petco_Park%2C_San_Diego.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Gaslamp_Quarter_01.jpg/1920px-Gaslamp_Quarter_01.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/San_Diego_Reflecting_Pond.jpg/1920px-San_Diego_Reflecting_Pond.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/San_Diego_Skyline_Day_JD111107.jpg/1920px-San_Diego_Skyline_Day_JD111107.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/San_Diego_Skyline_Night_JD081107.jpg/1920px-San_Diego_Skyline_Night_JD081107.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/SanDiegoSkyline.jpg/1920px-SanDiegoSkyline.jpg",
  ],
  "los-angeles": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Los_Angeles_with_Mount_Baldy.jpg/1920px-Los_Angeles_with_Mount_Baldy.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/DTLA_%2850880465741%29.jpg/1920px-DTLA_%2850880465741%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Walt_Disney_Concert_Hall%2C_LA%2C_CA%2C_jjron_22.03.2012.jpg/1920px-Walt_Disney_Concert_Hall%2C_LA%2C_CA%2C_jjron_22.03.2012.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Los_Angeles_Pollution.jpg/1920px-Los_Angeles_Pollution.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Los_Angeles_Skyline_at_Night.jpg/1920px-Los_Angeles_Skyline_at_Night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Los_Angeles_Skyline_via_Elysian_Park.JPG/1920px-Los_Angeles_Skyline_via_Elysian_Park.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Los_Angeles_Skyline_telephoto_%282%29.jpg/1920px-Los_Angeles_Skyline_telephoto_%282%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Los_Angeles_skyline_2.jpg/1920px-Los_Angeles_skyline_2.jpg",
  ],
  "san-francisco": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Financial_District%2C_San_Francisco.jpg/1920px-Financial_District%2C_San_Francisco.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/San_Francisco_Downtown_Aerial%2C_August_2025.jpg/1920px-San_Francisco_Downtown_Aerial%2C_August_2025.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Painted_Ladies_San_Francisco_January_2013_panorama_2.jpg/1920px-Painted_Ladies_San_Francisco_January_2013_panorama_2.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/San_Francisco_at_Sunset.jpg/1920px-San_Francisco_at_Sunset.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/SanFrancisco_from_TwinPeaks_dusk_MC.jpg/1920px-SanFrancisco_from_TwinPeaks_dusk_MC.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/San_Francisco_with_approaching_fog.jpg/1920px-San_Francisco_with_approaching_fog.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Fort_Mason_Center_and_Downtown_San_Francisco.jpg/1920px-Fort_Mason_Center_and_Downtown_San_Francisco.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Pano_of_Golden_Gate_Bridge_and_San_Francisco_from_Twin_Peaks_1_1.jpg/1920px-Pano_of_Golden_Gate_Bridge_and_San_Francisco_from_Twin_Peaks_1_1.jpg",
  ],
  "chicago": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Chicago_Skyline_in_April_2024_b.jpg/1920px-Chicago_Skyline_in_April_2024_b.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Chicago_Skyline_in_September_2023_pano.jpg/1920px-Chicago_Skyline_in_September_2023_pano.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Full_chicago_skyline.jpg/1920px-Full_chicago_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Chicago_Downtown_Panorama.jpg/1920px-Chicago_Downtown_Panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Chicago_Skyline_Hi-Res.jpg/1920px-Chicago_Skyline_Hi-Res.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Chicago_sunrise_1.jpg/1920px-Chicago_sunrise_1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Skyline_de_Chicago_desde_el_centro%2C_Illinois%2C_Estados_Unidos%2C_2012-10-20%2C_DD_06.jpg/1920px-Skyline_de_Chicago_desde_el_centro%2C_Illinois%2C_Estados_Unidos%2C_2012-10-20%2C_DD_06.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Chicago_from_North_Avenue_Beach_June_2015_panorama_2.jpg/1920px-Chicago_from_North_Avenue_Beach_June_2015_panorama_2.jpg",
  ],
  "seattle": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Seattle_Downtown_Aerial%2C_July_2025_%28zoomed_and_perspective_corrected%29.jpg/1920px-Seattle_Downtown_Aerial%2C_July_2025_%28zoomed_and_perspective_corrected%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Seattle_skyline_panorama_from_Kerry_Park%2C_June_2022.jpg/1920px-Seattle_skyline_panorama_from_Kerry_Park%2C_June_2022.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Seattle_downtown_from_smith_tower.jpg/1920px-Seattle_downtown_from_smith_tower.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/SeattleI5Skyline.jpg/1920px-SeattleI5Skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Seattle_3.jpg/1920px-Seattle_3.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Seattle_7.jpg/1920px-Seattle_7.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Seattle_Skyline_At_Night.jpg/1920px-Seattle_Skyline_At_Night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Seattle_Skyline-.jpg/1920px-Seattle_Skyline-.jpg",
  ],
  "new-york": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Skyline-New-York-City.jpg/1920px-Skyline-New-York-City.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/New_York_City_at_night_HDR.jpg/1920px-New_York_City_at_night_HDR.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/New_York_Midtown_Skyline_at_night_-_Jan_2006_edit1.jpg/1920px-New_York_Midtown_Skyline_at_night_-_Jan_2006_edit1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/New_York_City_%28New_York%2C_USA%29%2C_Central_Park_--_2012_--_6731.jpg/1920px-New_York_City_%28New_York%2C_USA%29%2C_Central_Park_--_2012_--_6731.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/New_York_City_%28New_York%2C_USA%29%2C_Empire_State_Building_--_2012_--_6448_%28bw%29.jpg/1920px-New_York_City_%28New_York%2C_USA%29%2C_Empire_State_Building_--_2012_--_6448_%28bw%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Lower_Manhattan_from_Jersey_City_November_2014_panorama_2.jpg/1920px-Lower_Manhattan_from_Jersey_City_November_2014_panorama_2.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Lower_Manhattan_from_Jersey_City_November_2014_panorama_3.jpg/1920px-Lower_Manhattan_from_Jersey_City_November_2014_panorama_3.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Long_Island_City_New_York_May_2015_panorama_3.jpg/1920px-Long_Island_City_New_York_May_2015_panorama_3.jpg",
  ],
  "colorado-springs": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Colorado_Springs_Skyline_%2854557268110%29.jpg/1920px-Colorado_Springs_Skyline_%2854557268110%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Downtown_Colorado_Springs_3_by_David_Shankbone.jpg/1920px-Downtown_Colorado_Springs_3_by_David_Shankbone.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Downtown_Colorado_Springs_from_the_east.jpg/1920px-Downtown_Colorado_Springs_from_the_east.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Downtown_Colorado_Springs_by_David_Shankbone_cropped.jpg/1920px-Downtown_Colorado_Springs_by_David_Shankbone_cropped.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Downtown_Colorado_Springs_by_David_Shankbone.jpg/1920px-Downtown_Colorado_Springs_by_David_Shankbone.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/CoSpgs161.jpg/1920px-CoSpgs161.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/CC_COSPRINGS.jpg/1920px-CC_COSPRINGS.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Colorado_Springs%2C_downtown%2C_1950%27s.jpg/1920px-Colorado_Springs%2C_downtown%2C_1950%27s.jpg",
  ],
  "detroit": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Detroit_Skyline_from_Windsor_2025-09-01.jpg/1920px-Detroit_Skyline_from_Windsor_2025-09-01.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Renaissance_Center%2C_Detroit%2C_Michigan_from_S_2014-12-07.jpg/1920px-Renaissance_Center%2C_Detroit%2C_Michigan_from_S_2014-12-07.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Campus_Martius%2C_Detroit%2C_MI.jpg/1920px-Campus_Martius%2C_Detroit%2C_MI.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Detroit_Skyline_1942d.jpg/1920px-Detroit_Skyline_1942d.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Detroit_Night_Skyline_Cropped_2.JPG/1920px-Detroit_Night_Skyline_Cropped_2.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Skyline_of_Detroit%2C_Michigan_from_S_2014-12-07.jpg/1920px-Skyline_of_Detroit%2C_Michigan_from_S_2014-12-07.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Belle_Isle_Bridge_and_Ambassador_Bridge%2C_against_Detroit%27s_Skyline%2C_Detroit%2C_Mich_%2872685%29.jpg/1920px-Belle_Isle_Bridge_and_Ambassador_Bridge%2C_against_Detroit%27s_Skyline%2C_Detroit%2C_Mich_%2872685%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Detroit_Skyline_%28123143197%29.jpeg/1920px-Detroit_Skyline_%28123143197%29.jpeg",
  ],
  "washington-dc": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/DC_Capitol_Historic_District.jpg/1920px-DC_Capitol_Historic_District.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/USA-Georgetown_C%26O_Canal.jpg/1920px-USA-Georgetown_C%26O_Canal.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Union_Station_Washington_DC.jpg/1920px-Union_Station_Washington_DC.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Skyline_of_Washington%2C_seen_from_Saint_Elizabeths%2C_August_23%2C_2006.jpg/1920px-Skyline_of_Washington%2C_seen_from_Saint_Elizabeths%2C_August_23%2C_2006.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Washington_DC_Panorama.jpg/1920px-Washington_DC_Panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Georgetown%2C_Washington%2C_D.C._HDR.jpg/1920px-Georgetown%2C_Washington%2C_D.C._HDR.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/US_Navy_040709-N-0295M-004_The_Washington_Monument_and_Thomas_Jefferson_Memorial_fill_the_skyline_of_Washington%2C_D.C.jpg/1920px-US_Navy_040709-N-0295M-004_The_Washington_Monument_and_Thomas_Jefferson_Memorial_fill_the_skyline_of_Washington%2C_D.C.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Washington_dc_skyline.jpg/1920px-Washington_dc_skyline.jpg",
  ],
  "boston": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Boston_skyline_from_Longfellow_Bridge_September_2017_panorama_2.jpg/1920px-Boston_skyline_from_Longfellow_Bridge_September_2017_panorama_2.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Federal_Reserve_from_South_Boston.jpg/1920px-Federal_Reserve_from_South_Boston.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Old_State_House_%2849280448012%29.jpg/1920px-Old_State_House_%2849280448012%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Boston_Financial_District_skyline.jpg/1920px-Boston_Financial_District_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Boston_skyline_from_Boston_Harbor.jpg/1920px-Boston_skyline_from_Boston_Harbor.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Boston_skyline_from_Malone_Park%2C_Chelsea%2C_February_2014.jpg/1920px-Boston_skyline_from_Malone_Park%2C_Chelsea%2C_February_2014.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Boston_skyline_from_Cambridge_November_2015_panorama_1.jpg/1920px-Boston_skyline_from_Cambridge_November_2015_panorama_1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Boston_skyline_from_East_Boston_November_2016_panorama_1.jpg/1920px-Boston_skyline_from_East_Boston_November_2016_panorama_1.jpg",
  ],
  "philadelphia": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Philadelphia_skyline_20240528_%28cropped_2-1%29.jpg/1920px-Philadelphia_skyline_20240528_%28cropped_2-1%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/A651%2C_Philadelphia_skyline_from_the_Spring_Garden_Street_Bridge%2C_2018.jpg/1920px-A651%2C_Philadelphia_skyline_from_the_Spring_Garden_Street_Bridge%2C_2018.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Gathering_Storm_Over_Philadelphia_-_NARA_-_559357.jpg/1920px-Gathering_Storm_Over_Philadelphia_-_NARA_-_559357.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Ferdinand_Richardt_-_Independence_Hall_in_Philadelphia_-_Google_Art_Project.jpg/1920px-Ferdinand_Richardt_-_Independence_Hall_in_Philadelphia_-_Google_Art_Project.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Philadelphia_cityscape_BW_20150328.jpg/1920px-Philadelphia_cityscape_BW_20150328.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Philadelphia_from_South_Street_Bridge_July_2016_panorama_1.jpg/1920px-Philadelphia_from_South_Street_Bridge_July_2016_panorama_1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Philadelphia_from_South_Street_Bridge_July_2016_panorama_2.jpg/1920px-Philadelphia_from_South_Street_Bridge_July_2016_panorama_2.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Philadelphia_from_South_Street_Bridge_July_2016_panorama_3.jpg/1920px-Philadelphia_from_South_Street_Bridge_July_2016_panorama_3.jpg",
  ],
  "oakland": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Grand_Avenue_side_of_Lake_Merritt%2C_Oakland.jpg/1920px-Grand_Avenue_side_of_Lake_Merritt%2C_Oakland.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Lake_Merritt_2022-06-16.png/1920px-Lake_Merritt_2022-06-16.png",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Oakland_Skyline_and_Lake_Merritt.jpg/1920px-Oakland_Skyline_and_Lake_Merritt.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Oakland_skyline%2C_dusk.jpg/1920px-Oakland_skyline%2C_dusk.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Oakland_Skyline_Telephoto.jpg/1920px-Oakland_Skyline_Telephoto.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Oakland_Skyline_-_Lake_Merritt.jpg/1920px-Oakland_Skyline_-_Lake_Merritt.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/OAKLAND%2C_CA%2C_USA_-_Skyline_and_Bridge.JPG/1920px-OAKLAND%2C_CA%2C_USA_-_Skyline_and_Bridge.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/OAKLAND%2C_CA%2C_USA_-_Night_Skyline_with_Bay_Bridge.jpg/1920px-OAKLAND%2C_CA%2C_USA_-_Night_Skyline_with_Bay_Bridge.jpg",
  ],
  "cincinnati": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Downtown_Cincinnati_viewed_from_Devou_Park_%28cropped%29.jpg/1920px-Downtown_Cincinnati_viewed_from_Devou_Park_%28cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Downtown_Cincinnati_viewed_from_Mt._Adams_%28cropped%29.jpg/1920px-Downtown_Cincinnati_viewed_from_Mt._Adams_%28cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cincinnati_Union_Terminal_principal_facade.jpg/1920px-Cincinnati_Union_Terminal_principal_facade.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Cincinnati-skyline-chili-exterior.jpg/1920px-Cincinnati-skyline-chili-exterior.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cincinnati_Skyline_002.JPG/1920px-Cincinnati_Skyline_002.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Cincinnati_Skyline_003.JPG/1920px-Cincinnati_Skyline_003.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Cincinnati_Skyline_Night_Ballpark.JPG/1920px-Cincinnati_Skyline_Night_Ballpark.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Cincinnati_skyline_%28at_night%29.jpg/1920px-Cincinnati_skyline_%28at_night%29.jpg",
  ],
  "new-orleans": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/New_Orleans_from_the_Air_September_2019_-_Central_Business_District_Skyline_%28cropped%29.jpg/1920px-New_Orleans_from_the_Air_September_2019_-_Central_Business_District_Skyline_%28cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/New_Orleans_Skyline_from_Uptown.jpg/1920px-New_Orleans_Skyline_from_Uptown.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Stlouiscathedralnight.jpg/1920px-Stlouiscathedralnight.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/French_Quarter03_New_Orleans.JPG/1920px-French_Quarter03_New_Orleans.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/New_Orleans_1977_Night_Skyline_-_Lykes_Building_World_Trade_Mart_Hilton.jpg/1920px-New_Orleans_1977_Night_Skyline_-_Lykes_Building_World_Trade_Mart_Hilton.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/New_Orleans_1977_Night_Skyline_Lykes_Building_World_Trade_Mart.jpg/1920px-New_Orleans_1977_Night_Skyline_Lykes_Building_World_Trade_Mart.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/New_Orleans_skyline_2012_from_Danziger.jpg/1920px-New_Orleans_skyline_2012_from_Danziger.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/New_Orleans_skyline-02.jpg/1920px-New_Orleans_skyline-02.jpg",
  ],
  "baton-rouge": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Downtown_Baton_Rouge%2C_Louisiana_from_Tiger_Stadium_%28LSU%29.jpg/1920px-Downtown_Baton_Rouge%2C_Louisiana_from_Tiger_Stadium_%28LSU%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Baton_Rouge_-_Old_State_Capitol_from_the_riverfront%2C_April_2024.jpg/1920px-Baton_Rouge_-_Old_State_Capitol_from_the_riverfront%2C_April_2024.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Baton_Rouge_riverfront_from_I-10_bridge_5_November_2016_-_1.jpg/1920px-Baton_Rouge_riverfront_from_I-10_bridge_5_November_2016_-_1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Baton_Rouge_Panorama_1912.jpg/1920px-Baton_Rouge_Panorama_1912.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/BatonRouge360.jpg/1920px-BatonRouge360.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Baton_Rouge_at_the_River_5.14.11.jpg/1920px-Baton_Rouge_at_the_River_5.14.11.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Baton_Rouge_Upriver_from_I-10_Bridge.jpg/1920px-Baton_Rouge_Upriver_from_I-10_Bridge.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/ExxonMobil_Baton_Rouge.jpg/1920px-ExxonMobil_Baton_Rouge.jpg",
  ],
  "cambridge": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Cambridge_skyline_November_2016_panorama.jpg/1920px-Cambridge_skyline_November_2016_panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Harvard_Yard_in_autumn%2C_Boston%2C_Massachusetts%2C_2015.jpg/1920px-Harvard_Yard_in_autumn%2C_Boston%2C_Massachusetts%2C_2015.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/MIT_Main_Campus_Aerial.jpg/1920px-MIT_Main_Campus_Aerial.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Harvard_river_houses_2008_aerial_view.jpg/1920px-Harvard_river_houses_2008_aerial_view.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/North_and_West_Cambridge_and_North_Allston_aerial.JPG/1920px-North_and_West_Cambridge_and_North_Allston_aerial.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/View_of_Cambridge_from_Boston_Gary_Kirk_Brown_4.jpg/1920px-View_of_Cambridge_from_Boston_Gary_Kirk_Brown_4.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Cambridge_Highlands_aerial%2C_November_2015.jpg/1920px-Cambridge_Highlands_aerial%2C_November_2015.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Massachusetts_Hall%2C_Harvard_University.JPG/1920px-Massachusetts_Hall%2C_Harvard_University.JPG",
  ],
  "dallas": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/View_of_Dallas_from_Reunion_Tower_August_2015_05.jpg/1920px-View_of_Dallas_from_Reunion_Tower_August_2015_05.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Klyde_Warren_Park_and_Dallas%27_Skyline.jpg/1920px-Klyde_Warren_Park_and_Dallas%27_Skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Dallas%2C_Texas_Skyline_2005.jpg/1920px-Dallas%2C_Texas_Skyline_2005.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Dallas_skyline_1912.jpg/1920px-Dallas_skyline_1912.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Dallas_skyline_1912c.jpg/1920px-Dallas_skyline_1912c.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Dallas%2C_Texas_Skyline_1912.jpg/1920px-Dallas%2C_Texas_Skyline_1912.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Dallas_skyline_and_suburbs.jpg/1920px-Dallas_skyline_and_suburbs.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Dallas_Skyline-01.jpg/1920px-Dallas_Skyline-01.jpg",
  ],
  "charlotte": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Uptown_Charlotte_2018_taking_by_DJI_Phantom_4_pro.jpg/1920px-Uptown_Charlotte_2018_taking_by_DJI_Phantom_4_pro.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Romare_Bearden_Park_2.JPG/1920px-Romare_Bearden_Park_2.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Panorama_of_Charlotte%2C_North_Carolina%2C_seen_from_Hearn_and_Graham_facing_east_%282005%29.jpg/1920px-Panorama_of_Charlotte%2C_North_Carolina%2C_seen_from_Hearn_and_Graham_facing_east_%282005%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Charlotte%2C_NC_skyline%2C_Jan._2010.jpg/1920px-Charlotte%2C_NC_skyline%2C_Jan._2010.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Tryon_and_Stonewall%2C_Charlotte%2C_North_Carolina.jpg/1920px-Tryon_and_Stonewall%2C_Charlotte%2C_North_Carolina.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/South_End%2C_Charlotte%2C_North_Carolina.jpg/1920px-South_End%2C_Charlotte%2C_North_Carolina.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Charlotte_Skyline_during_the_morning.jpg/1920px-Charlotte_Skyline_during_the_morning.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Timelapse_of_Charlotte_Skyline.jpg/1920px-Timelapse_of_Charlotte_Skyline.jpg",
  ],
  "baltimore": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Skyline_of_Baltimore.jpg/1920px-Skyline_of_Baltimore.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Baltimore_Skyline.jpg/1920px-Baltimore_Skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Baltimore_Inner_Harbor_from_Federal_Hill.jpg/1920px-Baltimore_Inner_Harbor_from_Federal_Hill.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Baltimore_Inner_Harbor_Skyline_Night_Panorama.jpg/1920px-Baltimore_Inner_Harbor_Skyline_Night_Panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Baltimore_Skyline-02.jpg/1920px-Baltimore_Skyline-02.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Inner_Harbor_Skyline_View.JPG/1920px-Inner_Harbor_Skyline_View.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Baltimore_Skyline_-_panoramio.jpg/1920px-Baltimore_Skyline_-_panoramio.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Pratt_Street_skyline_from_Convention_Center%2C_Baltimore%2C_MD.jpg/1920px-Pratt_Street_skyline_from_Convention_Center%2C_Baltimore%2C_MD.jpg",
  ],
  "minneapolis": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Minneapolis_Skyline_looking_south.jpg/1920px-Minneapolis_Skyline_looking_south.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Stone_Arch_Bridge_as_viewed_from_downriver_2019-08-08_%28cropped%29.jpg/1920px-Stone_Arch_Bridge_as_viewed_from_downriver_2019-08-08_%28cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Minneapolis-skyline-2007-05-05.jpg/1920px-Minneapolis-skyline-2007-05-05.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Minneapolis-skyline-20070508.jpg/1920px-Minneapolis-skyline-20070508.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Minneapolis_Skyline_Sunset.jpg/1920px-Minneapolis_Skyline_Sunset.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Minneapolis_skyline_from_Walker_1.jpg/1920px-Minneapolis_skyline_from_Walker_1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Minneapolis_skyline_151.jpg/1920px-Minneapolis_skyline_151.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Minneapolis_skyline_51.JPG/1920px-Minneapolis_skyline_51.JPG",
  ],
  "cleveland": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Cleveland_skyline_from_Lakewood_Park%2C_January_2026.jpg/1920px-Cleveland_skyline_from_Lakewood_Park%2C_January_2026.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Rock_and_Roll_Hall_of_Fame_-_Joy_of_Museums_1.jpg/1920px-Rock_and_Roll_Hall_of_Fame_-_Joy_of_Museums_1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Cleveland_Public_Square_Fountain_%2829744768716%29.jpg/1920px-Cleveland_Public_Square_Fountain_%2829744768716%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Downtown_panorama.jpg/1920px-Downtown_panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Illuminated_West_Side_Market.jpg/1920px-Illuminated_West_Side_Market.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Cleveland_Skyline_2015.png/1920px-Cleveland_Skyline_2015.png",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Cleveland_Rainy_Night_%2817130409821%29.jpg/1920px-Cleveland_Rainy_Night_%2817130409821%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Cleveland%2C_Ohio_%2820398032692%29.jpg/1920px-Cleveland%2C_Ohio_%2820398032692%29.jpg",
  ],
  "milwaukee": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Calatrava_-_Milwaukee_Art_Museum%2C_Quadracci_Pavilion_%28AAAA%29.jpg/1920px-Calatrava_-_Milwaukee_Art_Museum%2C_Quadracci_Pavilion_%28AAAA%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Entrance_to_the_Historic_Third_Ward.jpg/1920px-Entrance_to_the_Historic_Third_Ward.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Milwaukee_05741u.jpg/1920px-Milwaukee_05741u.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Milwaukee_Riverwalk_in_Milwaukee_photographed_in_June_2024_%E2%80%947089.jpg/1920px-Milwaukee_Riverwalk_in_Milwaukee_photographed_in_June_2024_%E2%80%947089.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Milwaukee_June_2025_006_%28Lakefront_Brewery%29.jpg/1920px-Milwaukee_June_2025_006_%28Lakefront_Brewery%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Milwaukee_Cathedral_3.jpg/1920px-Milwaukee_Cathedral_3.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Milwaukee_March_2024_2_%28Milwaukee_skyline_from_Kadish_Park%29.jpg/1920px-Milwaukee_March_2024_2_%28Milwaukee_skyline_from_Kadish_Park%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Milwaukee_September_2023_004_%28Milwaukee_Public_Market%29.jpg/1920px-Milwaukee_September_2023_004_%28Milwaukee_Public_Market%29.jpg",
  ],
  "las-vegas": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Las_Vegas_from_above_%2840064746644%29.jpg/1920px-Las_Vegas_from_above_%2840064746644%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Las_Vegas_at_Night.JPG/1920px-Las_Vegas_at_Night.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/LasVegasSymphonyPark1.jpg/1920px-LasVegasSymphonyPark1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Las_Vegas_Strip_panorama.jpg/1920px-Las_Vegas_Strip_panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Las_Vegas_63.jpg/1920px-Las_Vegas_63.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Las_Vegas_Strip_at_night%2C_2012.jpg/1920px-Las_Vegas_Strip_at_night%2C_2012.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Las_Vegas_Strip_at_day_2013.jpg/1920px-Las_Vegas_Strip_at_day_2013.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Bellagio_Las_Vegas_December_2013_panorama.jpg/1920px-Bellagio_Las_Vegas_December_2013_panorama.jpg",
  ],
  "boise": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Boise_Downtown_Panoramic.jpg/1920px-Boise_Downtown_Panoramic.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Idaho_Capitol_Building.JPG/1920px-Idaho_Capitol_Building.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Idaho_-_Boise_through_Boise_River_-_NARA_-_23939399_%28cropped%29.jpg/1920px-Idaho_-_Boise_through_Boise_River_-_NARA_-_23939399_%28cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Hyde_Park_Boise.jpg/1920px-Hyde_Park_Boise.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Downtown_Boise_in_Fall.jpg/1920px-Downtown_Boise_in_Fall.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Boise_Skyline_Night.JPG/1920px-Boise_Skyline_Night.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Boise_Sunset.jpg/1920px-Boise_Sunset.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Boise_banner.jpg/1920px-Boise_banner.jpg",
  ],
  "buffalo": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Buffalo%2C_NY_skyline.jpg/1920px-Buffalo%2C_NY_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/AllentownBuffalo1.jpg/1920px-AllentownBuffalo1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Shea%27s_Buffalo_Theater%2C_Main_Street%2C_Buffalo%2C_NY.jpg/1920px-Shea%27s_Buffalo_Theater%2C_Main_Street%2C_Buffalo%2C_NY.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Leaving_downtown_Buffalo%2C_New_York_via_I-190_North.jpg/1920px-Leaving_downtown_Buffalo%2C_New_York_via_I-190_North.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Downtown_Buffalo_skyline_as_seen_from_rear_of_former_Seaway_Trail_Center%2C_Hamburg%2C_New_York_-_20190723.jpg/1920px-Downtown_Buffalo_skyline_as_seen_from_rear_of_former_Seaway_Trail_Center%2C_Hamburg%2C_New_York_-_20190723.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Downtown_skyline_and_grain_elevators_as_seen_from_Buffalo_Harbor_State_Park%2C_Buffalo%2C_New_York_-_20190724.jpg/1920px-Downtown_skyline_and_grain_elevators_as_seen_from_Buffalo_Harbor_State_Park%2C_Buffalo%2C_New_York_-_20190724.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Downtown_Buffalo_skyline_seen_distantly_from_Chestnut_Ridge_Park%2C_Orchard_Park%2C_New_York_-_20190810.jpg/1920px-Downtown_Buffalo_skyline_seen_distantly_from_Chestnut_Ridge_Park%2C_Orchard_Park%2C_New_York_-_20190810.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Downtown_Buffalo_skyline_as_seen_from_Chestnut_Ridge_Park_%28telephoto_view%29%2C_Orchard_Park%2C_New_York_-_20190810.jpg/1920px-Downtown_Buffalo_skyline_as_seen_from_Chestnut_Ridge_Park_%28telephoto_view%29%2C_Orchard_Park%2C_New_York_-_20190810.jpg",
  ],
  "norfolk": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Norfolk%2C_Virginia_skyline_2016.jpg/1920px-Norfolk%2C_Virginia_skyline_2016.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Skyline_of_Downtown_Norfolk_Looking_Towards_Portsmouth.jpg/1920px-Skyline_of_Downtown_Norfolk_Looking_Towards_Portsmouth.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Downtown_Norfolk_VA_skyline_Nov_2021.jpg/1920px-Downtown_Norfolk_VA_skyline_Nov_2021.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Norfolk_VA_from_Portsmouth_2020.jpg/1920px-Norfolk_VA_from_Portsmouth_2020.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Norfolk_naval_base_aerial_1985.jpg/1920px-Norfolk_naval_base_aerial_1985.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/USS_George_Washington_in_Norfolk_Naval_Station.jpg/1920px-USS_George_Washington_in_Norfolk_Naval_Station.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Norfolk_Naval_Shipyard_aerial_photo_in_1995.JPEG/1920px-Norfolk_Naval_Shipyard_aerial_photo_in_1995.JPEG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Norfolk%2C_Virginia_skyline.jpg/1920px-Norfolk%2C_Virginia_skyline.jpg",
  ],
  "kansas-city": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Kansas_City%2C_MO_Union_Station_%283557621442%29.jpg/1920px-Kansas_City%2C_MO_Union_Station_%283557621442%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Kansas_City_Panorama.jpg/1920px-Kansas_City_Panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Kansas_City_skyline_as_night_descends.jpg/1920px-Kansas_City_skyline_as_night_descends.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Downtown_Kansas_City%2C_Missouri_from_Liberty_Memorial.jpg/1920px-Downtown_Kansas_City%2C_Missouri_from_Liberty_Memorial.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Downtown_kansas_city_2010-03-07.png/1920px-Downtown_kansas_city_2010-03-07.png",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Kansas_City%2C_MO_skyline_at_night.jpg/1920px-Kansas_City%2C_MO_skyline_at_night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Skyline_Kansas_City_2008.jpg/1920px-Skyline_Kansas_City_2008.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Kansas_City_Skyline.jpg/1920px-Kansas_City_Skyline.jpg",
  ],
  "saint-paul": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Cathedral_of_St._Paul_from_the_Landmark_Center.jpg/1920px-Cathedral_of_St._Paul_from_the_Landmark_Center.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Minnesota_State_Capitol_2017.jpg/1920px-Minnesota_State_Capitol_2017.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Skyline_Towers.JPG/1920px-Skyline_Towers.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Skyline_Towers_2.JPG/1920px-Skyline_Towers_2.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Saint_Paul%2C_Minnesota_9.jpg/1920px-Saint_Paul%2C_Minnesota_9.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Saint_Paul%2C_Minnesota_10.jpg/1920px-Saint_Paul%2C_Minnesota_10.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/St_Paul_Skyline_7_11_2007.jpg/1920px-St_Paul_Skyline_7_11_2007.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Saint_Paul_Riverfront_Pano.jpg/1920px-Saint_Paul_Riverfront_Pano.jpg",
  ],
  "pittsburgh": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Pittsburgh_skyline_panorama_at_night.jpg/1920px-Pittsburgh_skyline_panorama_at_night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Ascending_the_Duquesne_Incline.jpg/1920px-Ascending_the_Duquesne_Incline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Pittsburgh_-_Acrisure_Stadium_and_Skyline_%2853910936115%29.jpg/1920px-Pittsburgh_-_Acrisure_Stadium_and_Skyline_%2853910936115%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Pittsburgh_dawn_city_pano.jpg/1920px-Pittsburgh_dawn_city_pano.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Pittsburgh_skyline_night.jpg/1920px-Pittsburgh_skyline_night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Pittsburgh_Skyline_Day.jpg/1920px-Pittsburgh_Skyline_Day.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Pittsburgh_Skyline_1.jpg/1920px-Pittsburgh_Skyline_1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Pittsburgh_Skyline_2.jpg/1920px-Pittsburgh_Skyline_2.jpg",
  ],
  "fort-worth": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Downtown_Fort_Worth.jpg/1920px-Downtown_Fort_Worth.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Sundance_Square.jpg/1920px-Sundance_Square.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Fort_Worth_Stockyards.jpg/1920px-Fort_Worth_Stockyards.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Fort_Worth%2C_Texas_at_Sunset.jpg/1920px-Fort_Worth%2C_Texas_at_Sunset.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Ft_worth_skyline_downtown_v.jpg/1920px-Ft_worth_skyline_downtown_v.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Fort_Worth_Skyline_at_Sunset.jpg/1920px-Fort_Worth_Skyline_at_Sunset.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Fort_Worth_June_2016_68_%28skyline%29.jpg/1920px-Fort_Worth_June_2016_68_%28skyline%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Fort_Worth_Skyline.jpg/1920px-Fort_Worth_Skyline.jpg",
  ],
  "denver": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Denver%2C_Colorado_skyline_%28cropped%29.jpg/1920px-Denver%2C_Colorado_skyline_%28cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Denver%2C_Colorado_skyline.jpg/1920px-Denver%2C_Colorado_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Denver%2C_Colorado_skyline_%28cropped_3x5%29.jpg/1920px-Denver%2C_Colorado_skyline_%28cropped_3x5%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Denver_Colorado_09570u.jpg/1920px-Denver_Colorado_09570u.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Denver_Skyscrapers_with_Daniels_and_Fischer_tower.JPG/1920px-Denver_Skyscrapers_with_Daniels_and_Fischer_tower.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/CO_Denver_1915.jpg/1920px-CO_Denver_1915.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/CO_Denver_1907.jpg/1920px-CO_Denver_1907.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/CO_Denver_1887.jpg/1920px-CO_Denver_1887.jpg",
  ],
  "sacramento": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sacramento_Skyline_%28cropped%29.jpg/1920px-Sacramento_Skyline_%28cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Sacramento%2C_California_skyline_in_2023.jpg/1920px-Sacramento%2C_California_skyline_in_2023.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Sacramento%2C_California_skyline_2026.jpg/1920px-Sacramento%2C_California_skyline_2026.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Sacramento%2C_California_skyline.jpg/1920px-Sacramento%2C_California_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/City_Skyline_Raley_Field.JPG/1920px-City_Skyline_Raley_Field.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Sacramento_Skyline.jpg/1920px-Sacramento_Skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Sacramento_Night_Skyline.jpg/1920px-Sacramento_Night_Skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/NightSacramentoSkyline.jpg/1920px-NightSacramentoSkyline.jpg",
  ],
  "atlanta": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Atlanta_skyline_from_Jackson_Street_Bridge_2020.jpg/1920px-Atlanta_skyline_from_Jackson_Street_Bridge_2020.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Atlanta_Skyline_from_Buckhead.jpg/1920px-Atlanta_Skyline_from_Buckhead.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Marta_atlanta_skyline.jpg/1920px-Marta_atlanta_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Downtown_Atlanta_skyline_panorama.jpg/1920px-Downtown_Atlanta_skyline_panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Atlanta_skyline_from_Piedmont_Park_banner.jpg/1920px-Atlanta_skyline_from_Piedmont_Park_banner.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Jackson_Street_Bridge_and_Atlanta_Night_Skyline_%28Unsplash%29.jpg/1920px-Jackson_Street_Bridge_and_Atlanta_Night_Skyline_%28Unsplash%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Jackson_Street_Bridge%2C_Atlanta%2C_United_States_%28Unsplash_vXtX07KVcE8%29.jpg/1920px-Jackson_Street_Bridge%2C_Atlanta%2C_United_States_%28Unsplash_vXtX07KVcE8%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Atlanta_Skyline_%28142621079%29.jpeg/1920px-Atlanta_Skyline_%28142621079%29.jpeg",
  ],
  "indianapolis": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Indianapolis_skyline_-_2014_April_-_Chris_Bowman.jpg/1920px-Indianapolis_skyline_-_2014_April_-_Chris_Bowman.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/White_River_State_Park_Indianapolis_Skyline_2020.jpg/1920px-White_River_State_Park_Indianapolis_Skyline_2020.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Skyline_at_the_Indianapolis_Zoo_-_June_2022_-_Sarah_Stierch.jpg/1920px-Skyline_at_the_Indianapolis_Zoo_-_June_2022_-_Sarah_Stierch.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/IN_Indianapolis_1914.jpg/1920px-IN_Indianapolis_1914.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/IN_Indianapolis_1914a.jpg/1920px-IN_Indianapolis_1914a.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/View_of_downtown_Indianapolis_from_I-70.jpg/1920px-View_of_downtown_Indianapolis_from_I-70.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Downtown_Indianapolis_skyline%2C_looking_northeast.jpg/1920px-Downtown_Indianapolis_skyline%2C_looking_northeast.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Panorama_of_downtown_Indianapolis_skyline%2C_looking_northeast.jpg/1920px-Panorama_of_downtown_Indianapolis_skyline%2C_looking_northeast.jpg",
  ],
  "honolulu": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Panorama_of_Honolulu-Waikiki-Diamond_Head_%2816773142068%29.jpg/1920px-Panorama_of_Honolulu-Waikiki-Diamond_Head_%2816773142068%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Honolulu_-_panoramio.jpg/1920px-Honolulu_-_panoramio.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Waikiki_Beach.jpg/1920px-Waikiki_Beach.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Honolulu_Mayor_Peter_Carlisle_at_Rail_Groundbreaking_2011-02-22.jpg/1920px-Honolulu_Mayor_Peter_Carlisle_at_Rail_Groundbreaking_2011-02-22.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Honolulu_rail_project_construction_in_Waipahu_near_Fort_Weaver_Road_2015-07-29.jpg/1920px-Honolulu_rail_project_construction_in_Waipahu_near_Fort_Weaver_Road_2015-07-29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Honolulu_Skyline_%28Explored%29_-_Flickr_-_jijake1977.jpg/1920px-Honolulu_Skyline_%28Explored%29_-_Flickr_-_jijake1977.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Downtown_Honolulu.jpg/1920px-Downtown_Honolulu.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/HAWAII-DOWNTOWN%2C_HONOLULU_%28OAHU_I%29_-_NARA_-_553790.jpg/1920px-HAWAII-DOWNTOWN%2C_HONOLULU_%28OAHU_I%29_-_NARA_-_553790.jpg",
  ],
  "long-beach": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Downtown%2C_Long_Beach_from_Queen_Mary_%28Dusk%29.JPG/1920px-Downtown%2C_Long_Beach_from_Queen_Mary_%28Dusk%29.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Long_Beach_CA_Photo_D_Ramey_Logan.jpg/1920px-Long_Beach_CA_Photo_D_Ramey_Logan.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Downtown_Long_Beach_California_Aerial.jpg/1920px-Downtown_Long_Beach_California_Aerial.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Long_Beach_05.jpg/1920px-Long_Beach_05.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Long_Beach_07.jpg/1920px-Long_Beach_07.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Long_Beach_09.jpg/1920px-Long_Beach_09.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Downtown_Long_Beach.jpg/1920px-Downtown_Long_Beach.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Long_Beach_Oil_Field.jpg/1920px-Long_Beach_Oil_Field.jpg",
  ],
  "phoenix": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Phoenix_skyline_Arizona_USA.jpg/1920px-Phoenix_skyline_Arizona_USA.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Downtown_Phoenix_Skyline_%286974043971%29.jpg/1920px-Downtown_Phoenix_Skyline_%286974043971%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Downtown_Phoenix_Skyline_Lights.jpg/1920px-Downtown_Phoenix_Skyline_Lights.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Phoenix_Skyline_from_South_Mountain_at_Night.2010.jpg/1920px-Phoenix_Skyline_from_South_Mountain_at_Night.2010.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Downtown_Phoenix_Aerial_Looking_Northeast.jpg/1920px-Downtown_Phoenix_Aerial_Looking_Northeast.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Phoenix%2C_AZ.jpg/1920px-Phoenix%2C_AZ.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Downtown_Phoenix_Skyline_at_Night.jpg/1920px-Downtown_Phoenix_Skyline_at_Night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Downtown_Phoenix_banner.jpg/1920px-Downtown_Phoenix_banner.jpg",
  ],
  "jacksonville": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Jacksonville_Skyline_Panorama_2.jpg/1920px-Jacksonville_Skyline_Panorama_2.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Jacksonville_Skyline_Panorama_3.jpg/1920px-Jacksonville_Skyline_Panorama_3.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Skyline_of_Jacksonville_FL%2C_South_view_20160706_1.jpg/1920px-Skyline_of_Jacksonville_FL%2C_South_view_20160706_1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jacksonville_Florida_Night_Skyline_New_Year_2025.jpg/1920px-Jacksonville_Florida_Night_Skyline_New_Year_2025.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/P-3C_Orion_over_Jacksonville_Florida.jpg/1920px-P-3C_Orion_over_Jacksonville_Florida.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Aerial_View_of_Jacksonville_International_Airport.JPG/1920px-Aerial_View_of_Jacksonville_International_Airport.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Aerial_shot_of_Jacksonville%2C_Florida_in_the_1960s_%2810926432033%29.jpg/1920px-Aerial_shot_of_Jacksonville%2C_Florida_in_the_1960s_%2810926432033%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Aerial_shot_of_Jacksonville%2C_Florida_in_the_1960s_%2810926131485%29.jpg/1920px-Aerial_shot_of_Jacksonville%2C_Florida_in_the_1960s_%2810926131485%29.jpg",
  ],
  "virginia-beach": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/King_Neptune%2C_Virginia_Beach.jpg/1920px-King_Neptune%2C_Virginia_Beach.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Beach_at_Virginia_Beach_Oceanfront_01.jpg/1920px-Beach_at_Virginia_Beach_Oceanfront_01.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Virginia_Beach_from_Fishing_Pier.jpg/1920px-Virginia_Beach_from_Fishing_Pier.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/London_Bridge_Nursery_%28261301925%29.jpeg/1920px-London_Bridge_Nursery_%28261301925%29.jpeg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Virginia_Beach_City_Hall_%28243493177%29.jpeg/1920px-Virginia_Beach_City_Hall_%28243493177%29.jpeg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Virginia_Beach_from_Back_Bay_National_Wildlife_Refuge_2019.jpg/1920px-Virginia_Beach_from_Back_Bay_National_Wildlife_Refuge_2019.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Virginia_Beach_Boardwalk_-_October_9%2C_2022.jpg/1920px-Virginia_Beach_Boardwalk_-_October_9%2C_2022.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Beach_at_Virginia_Beach_Oceanfront_-_Paragliders.jpg/1920px-Beach_at_Virginia_Beach_Oceanfront_-_Paragliders.jpg",
  ],
  "gainesville": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Downtown_Gainesville%2C_FL.jpg/1920px-Downtown_Gainesville%2C_FL.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Gainesville%2C_FL_Downtown.jpg/1920px-Gainesville%2C_FL_Downtown.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Century_Tower_%28University_of_Florida%29.jpg/1920px-Century_Tower_%28University_of_Florida%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Ben_Hill_Griffin_Stadium_-_Florida_Gators.jpg/1920px-Ben_Hill_Griffin_Stadium_-_Florida_Gators.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Skyline_of_Gainsville%2C_Florida%2C_US.jpg/1920px-Skyline_of_Gainsville%2C_Florida%2C_US.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Gainesville_SFC_downtown_depot01.jpg/1920px-Gainesville_SFC_downtown_depot01.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Gainesville_SFC_downtown_depot02.jpg/1920px-Gainesville_SFC_downtown_depot02.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Gainesville_SFC_downtown_depot03.jpg/1920px-Gainesville_SFC_downtown_depot03.jpg",
  ],
  "tampa": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Tampa_Skyline_from_Ballast_Point_Park_April_2024.jpg/1920px-Tampa_Skyline_from_Ballast_Point_Park_April_2024.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Downtown_Tampa%2C_Florida.jpg/1920px-Downtown_Tampa%2C_Florida.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Tampa_Riverwalk_02.jpg/1920px-Tampa_Riverwalk_02.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Streetcar_-_Ybor_City_-_Tampa%2C_Florida%2C_2012.jpg/1920px-Streetcar_-_Ybor_City_-_Tampa%2C_Florida%2C_2012.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Downtown_Tampa_During_Gasparilla_Pirate_Fest_2002.jpg/1920px-Downtown_Tampa_During_Gasparilla_Pirate_Fest_2002.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Skyline_of_Tampa%2C_Florida_from_Bayshore_Blvd.jpg/1920px-Skyline_of_Tampa%2C_Florida_from_Bayshore_Blvd.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tampa_Skyline.jpg/1920px-Tampa_Skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Red_Bull_Flugtag_near_downtown_Tampa%2C_Florida_on_July_19%2C_2008_%28panorama%29.jpg/1920px-Red_Bull_Flugtag_near_downtown_Tampa%2C_Florida_on_July_19%2C_2008_%28panorama%29.jpg",
  ],
  // Nashville, TN — 8× 1920×1080 Wikimedia Commons cityscapes (HTTP-verified),
  // rotating on the same global CityBackdrop cadence as every other city.
  "nashville": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/It_is_the_Batman_Building_in_Nashville%2C_Tennessee-_%28Also_the_AT%26T_building-%29_2014-04-22_19-55.jpg/1920px-It_is_the_Batman_Building_in_Nashville%2C_Tennessee-_%28Also_the_AT%26T_building-%29_2014-04-22_19-55.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nashville%2C_TN_skyline.jpg/1920px-Nashville%2C_TN_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Nashville_From_Fort_Negley.jpg/1920px-Nashville_From_Fort_Negley.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Nashville_Skyline_at_Night_I-65.jpeg/1920px-Nashville_Skyline_at_Night_I-65.jpeg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Nashville_from_Shelby_Park_2024.jpg/1920px-Nashville_from_Shelby_Park_2024.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Nashville_pano_Opry_Broadway.jpg/1920px-Nashville_pano_Opry_Broadway.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Nashville_panorama.jpg/1920px-Nashville_panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Nashville_panorama_Kaldari_01.jpg/1920px-Nashville_panorama_Kaldari_01.jpg",
  ],
  // Houston, TX — 8× 1920×1080 Wikimedia Commons cityscapes (HTTP-verified).
  "houston": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Buildings-city-houston-skyline-1870617.jpg/1920px-Buildings-city-houston-skyline-1870617.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Downtown_Houston%2C_TX_Skyline_-_2018.jpg/1920px-Downtown_Houston%2C_TX_Skyline_-_2018.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Gfp-texas-houston-skyline-1.jpg/1920px-Gfp-texas-houston-skyline-1.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Gfp-texas-houston-skyline-buildings.jpg/1920px-Gfp-texas-houston-skyline-buildings.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Houston%2C_Texas_%282024%29_-_19.jpg/1920px-Houston%2C_Texas_%282024%29_-_19.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Houston%2C_Texas_Skyline_%2832614523857%29.jpg/1920px-Houston%2C_Texas_Skyline_%2832614523857%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Houston%2C_Texas_Skyline_2017.jpg/1920px-Houston%2C_Texas_Skyline_2017.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Houston_Skyline_-_Illustration.jpg/1920px-Houston_Skyline_-_Illustration.jpg",
  ],
  "montgomery-county": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Downtown_silver_spring_wayne.jpg/1920px-Downtown_silver_spring_wayne.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Georgia_Avenue_-_Silver_Spring%2C_Maryland_2021.jpg/1920px-Georgia_Avenue_-_Silver_Spring%2C_Maryland_2021.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Fenton_Building_-_Silver_Spring%2C_Maryland_04.jpg/1920px-Fenton_Building_-_Silver_Spring%2C_Maryland_04.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Georgia_Avenue_-_Silver_Spring%2C_Maryland_2022.jpg/1920px-Georgia_Avenue_-_Silver_Spring%2C_Maryland_2022.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Downtown_Silver_Spring%2C_Maryland.jpg/1920px-Downtown_Silver_Spring%2C_Maryland.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Music_Center_at_Strathmore_-_4.jpeg/1920px-Music_Center_at_Strathmore_-_4.jpeg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Music_Center_at_Strathmore_01.jpg/1920px-Music_Center_at_Strathmore_01.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Music_Center_at_Strathmore_02.jpg/1920px-Music_Center_at_Strathmore_02.jpg",
  ],
  "prince-georges-county": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/MGM_Grand_Opening_%2831159053010%29.jpg/1920px-MGM_Grand_Opening_%2831159053010%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/National_Harbor%2C_Maryland_03.jpg/1920px-National_Harbor%2C_Maryland_03.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/National_Harbor%2C_Maryland_08.jpg/1920px-National_Harbor%2C_Maryland_08.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/National_Harbor_aerial_2019.jpg/1920px-National_Harbor_aerial_2019.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Capital_Wheel_at_National_Harbor%2C_Maryland%2C_USA.jpg/1920px-Capital_Wheel_at_National_Harbor%2C_Maryland%2C_USA.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Capital_Wheel_at_National_Harbor%2C_Maryland%2C_USA_%28Lit_Up_at_Night%29.jpg/1920px-Capital_Wheel_at_National_Harbor%2C_Maryland%2C_USA_%28Lit_Up_at_Night%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Capital_Wheel_at_night.jpg/1920px-Capital_Wheel_at_night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/National_Harbor_Maryland_Capital_Wheel.jpg/1920px-National_Harbor_Maryland_Capital_Wheel.jpg",
  ],
  // v114 — expansion Wave-1 cities (8 verified Wikimedia Commons landscape
  // photos each, 1920px, HTTP-verified image/jpeg, recognizable city landmarks).
  "dayton": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Dayton-ohio-skyline.jpg/1920px-Dayton-ohio-skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/DaytonSkylineGMRiver.jpg/1920px-DaytonSkylineGMRiver.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/DaytonSkyline%2C_tenniscourts.jpg/1920px-DaytonSkyline%2C_tenniscourts.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Dayton_skyline_2.JPG/1920px-Dayton_skyline_2.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Dayton%2C_OH%2C_USA_-_panoramio_%281%29.jpg/1920px-Dayton%2C_OH%2C_USA_-_panoramio_%281%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Dayton%2C_Ohio.jpg/1920px-Dayton%2C_Ohio.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Dayton_Skyline_from_Patterson_Boulevard_and_5th_Street%2C_Dayton%2C_OH.jpg/1920px-Dayton_Skyline_from_Patterson_Boulevard_and_5th_Street%2C_Dayton%2C_OH.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Downtown_Dayton_from_Grafton_Hill%2C_Dayton%2C_OH.jpg/1920px-Downtown_Dayton_from_Grafton_Hill%2C_Dayton%2C_OH.jpg",
  ],
  "rochester": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Rochester_DT_08.JPG/1920px-Rochester_DT_08.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Rochester_HighFalls_Night.JPG/1920px-Rochester_HighFalls_Night.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Highfallsrochester.jpg/1920px-Highfallsrochester.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Skyline_Rochester%2C_NY.jpg/1920px-Skyline_Rochester%2C_NY.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Rochester_NY_Skyline.jpg/1920px-Rochester_NY_Skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Rochester_skyline%2C_looking_southeast.JPG/1920px-Rochester_skyline%2C_looking_southeast.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Rochester_skyline%2C_looking_south.JPG/1920px-Rochester_skyline%2C_looking_south.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rochester_skyline%2C_looking_southwest.JPG/1920px-Rochester_skyline%2C_looking_southwest.JPG",
  ],
  "raleigh": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Downtown_Raleigh_Skyline_viewed_from_Boylan_Ave.jpg/1920px-Downtown_Raleigh_Skyline_viewed_from_Boylan_Ave.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Raleigh%2C_NC_skyline.jpg/1920px-Raleigh%2C_NC_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/RaleighNC_skyline%2C_B%26W.jpg/1920px-RaleighNC_skyline%2C_B%26W.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/RaleighNC_skyline%2C_kudzu.jpg/1920px-RaleighNC_skyline%2C_kudzu.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Raleigh_skyline_in_1992.jpg/1920px-Raleigh_skyline_in_1992.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Downtown%2C_Raleigh%2C_North_Carolina%2C_USA_--_in_9_February_2014_h17m38_Cloudy_weather_--_%28panoramio.com%29.jpg/1920px-Downtown%2C_Raleigh%2C_North_Carolina%2C_USA_--_in_9_February_2014_h17m38_Cloudy_weather_--_%28panoramio.com%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Raleigh_downtown_skyline_-_panoramio.jpg/1920px-Raleigh_downtown_skyline_-_panoramio.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Raleigh%2C_North_Carolina_skyline_--_27_September_2014_%28panoramio.com%29.jpg/1920px-Raleigh%2C_North_Carolina_skyline_--_27_September_2014_%28panoramio.com%29.jpg",
  ],
  "grand-rapids": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Gr_skyline.jpg/1920px-Gr_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/GR%2C_MI_skyline.jpg/1920px-GR%2C_MI_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/GR_SKYLINE.JPG/1920px-GR_SKYLINE.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/2013_Grand_Rapids_flood.jpg/1920px-2013_Grand_Rapids_flood.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/2013_Grand_Rapids_flood_skyline.jpg/1920px-2013_Grand_Rapids_flood_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/City_on_The_River_%2822793909062%29.jpg/1920px-City_on_The_River_%2822793909062%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Grand_Rapids%2C_MI_skyline_2021.jpg/1920px-Grand_Rapids%2C_MI_skyline_2021.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Grand_Rapids_Skyline_%282022%29.jpg/1920px-Grand_Rapids_Skyline_%282022%29.jpg",
  ],
  "riverside": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Downtown_Riverside_Metrolink_Station.jpg/1920px-Downtown_Riverside_Metrolink_Station.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Downtown_Riverside%2C_Riverside%2C_CA%2C_USA_-_panoramio.jpg/1920px-Downtown_Riverside%2C_Riverside%2C_CA%2C_USA_-_panoramio.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Downtown_riverside.jpg/1920px-Downtown_riverside.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Metrolink_train_at_Riverside-Downtown_station%2C_December_2013.jpg/1920px-Metrolink_train_at_Riverside-Downtown_station%2C_December_2013.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Downtown_Riverside%2C_California_%285974691942%29.jpg/1920px-Downtown_Riverside%2C_California_%285974691942%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/California_Tower%2C_Downtown_Riverside%2C_California.jpg/1920px-California_Tower%2C_Downtown_Riverside%2C_California.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/California_-_Riverside_-_NARA_-_23934983.jpg/1920px-California_-_Riverside_-_NARA_-_23934983.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/California_-_Riverside_-_NARA_-_23934985.jpg/1920px-California_-_Riverside_-_NARA_-_23934985.jpg",
  ],
  "savannah": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Savannah_RiverSt_car756.jpg/1920px-Savannah_RiverSt_car756.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Savannah_River_St_Streetcar.jpg/1920px-Savannah_River_St_Streetcar.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Quintet_of_Young_Women_along_River_Street_-_Savannah_-_Georgia_-_USA_%2834346320631%29.jpg/1920px-Quintet_of_Young_Women_along_River_Street_-_Savannah_-_Georgia_-_USA_%2834346320631%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Moon_River_Brewing_Company_-_Savannah%2C_Georgia%2C_USA.jpg/1920px-Moon_River_Brewing_Company_-_Savannah%2C_Georgia%2C_USA.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/The_Jones_and_Derenne_Range%2C_Savannah%2C_GA%2C_US.jpg/1920px-The_Jones_and_Derenne_Range%2C_Savannah%2C_GA%2C_US.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/River_Street%2C_Savannah%2C_Georgia%2C_2017.jpg/1920px-River_Street%2C_Savannah%2C_Georgia%2C_2017.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Former_warehouses_facing_River_Street%2C_Savannah%2C_Georgia.jpg/1920px-Former_warehouses_facing_River_Street%2C_Savannah%2C_Georgia.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Buildings_facing_River_Street%2C_Savannah%2C_Georgia.jpg/1920px-Buildings_facing_River_Street%2C_Savannah%2C_Georgia.jpg",
  ],
  "corpus-christi": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Corpus_Christi_bay.jpg/1920px-Corpus_Christi_bay.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/City_of_Corpus_Christi_%28view_from_N%29%2C_Texas%2C_USA.JPG/1920px-City_of_Corpus_Christi_%28view_from_N%29%2C_Texas%2C_USA.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Downtown_Corpus_Christi%2C_Texas.JPG/1920px-Downtown_Corpus_Christi%2C_Texas.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Corpus_Christi01.JPG/1920px-Corpus_Christi01.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Bayfront_Corpus_Christi_Texas_at_Night.jpg/1920px-Bayfront_Corpus_Christi_Texas_at_Night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Corpus_Christi_1978_Skyline.jpg/1920px-Corpus_Christi_1978_Skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Corpus_Christi_TX_skyline.JPG/1920px-Corpus_Christi_TX_skyline.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Corpus_christi_tx_skyline_2014.jpg/1920px-Corpus_christi_tx_skyline_2014.jpg",
  ],
  // v115 — replacement-batch cities (8 verified Wikimedia Commons landscape
  // photos each, 1920px, HTTP-verified image/jpeg, recognizable landmarks).
  "salt-lake-city": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Temple_Square_1912_panorama.jpg/1920px-Temple_Square_1912_panorama.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Salt_Lake_City_-_July_16%2C_2011.jpg/1920px-Salt_Lake_City_-_July_16%2C_2011.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Salt_Lake_City_skyline%2C_August_2011.jpg/1920px-Salt_Lake_City_skyline%2C_August_2011.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Another_skyline_with_a_Trax_train.jpg/1920px-Another_skyline_with_a_Trax_train.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Salt_Lake_City%2C_May_2012.jpg/1920px-Salt_Lake_City%2C_May_2012.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Salt_Lake_City..._and_TRAX_%28again%29.jpg/1920px-Salt_Lake_City..._and_TRAX_%28again%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Salt_Lake_City_skyline_banner.jpg/1920px-Salt_Lake_City_skyline_banner.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Salt_Lake_City%2C_August_2012_%287707261420%29.jpg/1920px-Salt_Lake_City%2C_August_2012_%287707261420%29.jpg",
  ],
  "hartford": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hartford_Connecticut_Skyline.JPG/1920px-Hartford_Connecticut_Skyline.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/View_of_Connecticut_River_and_Hartford_Skyline%2C_Hartford%2C_Conn_%2867350%29.jpg/1920px-View_of_Connecticut_River_and_Hartford_Skyline%2C_Hartford%2C_Conn_%2867350%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/View_of_Connecticut_River%2C_and_Hartford_skyline%2C_Hartford%2C_Conn_%2867350%29.jpg/1920px-View_of_Connecticut_River%2C_and_Hartford_skyline%2C_Hartford%2C_Conn_%2867350%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Hartford_Skyline_from_Great_River_Park.jpg/1920px-Hartford_Skyline_from_Great_River_Park.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Hartford_Skyline_from_Great_River_Park_%28Cropped%29.jpg/1920px-Hartford_Skyline_from_Great_River_Park_%28Cropped%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Composite_of_hartford_skyline_on_a_clear_night_-_Flickr_-_TonySprezzatura.jpg/1920px-Composite_of_hartford_skyline_on_a_clear_night_-_Flickr_-_TonySprezzatura.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Hartford_skyline.jpg/1920px-Hartford_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Downtown_hartford_ct.jpg/1920px-Downtown_hartford_ct.jpg",
  ],
  "wichita": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Wichitanightskyline.jpg/1920px-Wichitanightskyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Downtown_ICT_Night.jpg/1920px-Downtown_ICT_Night.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Downtown_Wichita_From_Lincoln.jpg/1920px-Downtown_Wichita_From_Lincoln.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Wichita_Skyline_2021.jpg/1920px-Wichita_Skyline_2021.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Downtown_Wichita.jpg/1920px-Downtown_Wichita.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Wichita%2C_Kansas_skyline_aerial_view.jpg/1920px-Wichita%2C_Kansas_skyline_aerial_view.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Wichita%2C_Kansas_skyline.jpg/1920px-Wichita%2C_Kansas_skyline.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Wichita_pan_1.jpg/1920px-Wichita_pan_1.jpg",
  ],
  "tucson": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Tucson_skyline.JPG/1920px-Tucson_skyline.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Pinedo_Eli_Downtown_Tucson.jpg/1920px-Pinedo_Eli_Downtown_Tucson.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Downtown_Tucson_Arizona.JPG/1920px-Downtown_Tucson_Arizona.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Downtown_Tucson_Arizona_Colorful_Neighborhood_3.JPG/1920px-Downtown_Tucson_Arizona_Colorful_Neighborhood_3.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Downtown_Tucson_Arizona_Colorful_Neighborhood_1.JPG/1920px-Downtown_Tucson_Arizona_Colorful_Neighborhood_1.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Downtown_Tucson_Arizona_Colorful_Neighborhood_4.JPG/1920px-Downtown_Tucson_Arizona_Colorful_Neighborhood_4.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Downtown_Tucson_Arizona_Colorful_Neighborhood_6.JPG/1920px-Downtown_Tucson_Arizona_Colorful_Neighborhood_6.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/TucsonAMountainCity.jpg/1920px-TucsonAMountainCity.jpg",
  ],
  "albuquerque": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Abqdowntown.jpg/1920px-Abqdowntown.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Albuquerque_pano_sunset.jpg/1920px-Albuquerque_pano_sunset.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/DowntownAlbuquerqueSkyline.JPG/1920px-DowntownAlbuquerqueSkyline.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Albuquerque_Skyline.JPG/1920px-Albuquerque_Skyline.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/ABQ_downtown_skyline.JPG/1920px-ABQ_downtown_skyline.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Albuquerque_Rail_Shops.JPG/1920px-Albuquerque_Rail_Shops.JPG",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/ABQ-West-Mesa.jpg/1920px-ABQ-West-Mesa.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/View_from_Sandia_Peak_Tramway%2C_Albuquerque%2C_NM..jpg/1920px-View_from_Sandia_Peak_Tramway%2C_Albuquerque%2C_NM..jpg",
  ],
};
